import {useEffect,useState} from 'react';
import {apiBase,httpFetch,checkResponse} from '../../shared/http';
interface Participant {studentId:string;studentCode:string;enabled:boolean;createdAt:string;lastLoginAt:string|null;attemptCount:number}
interface Issued {participant:Participant;temporaryPassword:string}
export function Participants(){
 const [rows,setRows]=useState<Participant[]>([]);const [page,setPage]=useState(0);const [issued,setIssued]=useState<Issued|null>(null);const [error,setError]=useState(false);const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0);
 useEffect(()=>{const c=new AbortController();setError(false);void httpFetch(`${apiBase}/api/teacher/participants?page=${page}`,{signal:c.signal}).then(checkResponse).then(r=>r.json() as Promise<Participant[]>).then(setRows).catch(()=>{if(!c.signal.aborted)setError(true);});return()=>c.abort();},[page,revision]);
 async function action(path:string,method:string,body?:unknown){setBusy(true);setError(false);setIssued(null);try{const r=checkResponse(await httpFetch(`${apiBase}/api/teacher/participants${path}`,{method,headers:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})}));const result=await r.json() as Issued;if('temporaryPassword' in result)setIssued(result);setRevision(n=>n+1);}catch{setError(true);}finally{setBusy(false);}}
 return <section><h2>Participantes</h2><p>Administra únicamente el acceso. Las reglas y los parámetros pedagógicos permanecen en solo lectura.</p><button className="primary" disabled={busy} onClick={()=>{void action('','POST');}}>Crear participante</button>{issued&&<section aria-label="Clave temporal"><h3>{issued.participant.studentCode}</h3><p>Entrega esta clave al participante. Solo se muestra ahora; no podrá recuperarse después de cerrar este aviso.</p><code>{issued.temporaryPassword}</code><button onClick={()=>setIssued(null)}>Ocultar clave</button></section>}{error&&<p role="alert">No se pudo completar la operación. Comprueba la sesión y vuelve a intentar.</p>}<div className="meta-table"><table><thead><tr><th>Código</th><th>Estado</th><th>Creación</th><th>Último acceso</th><th>Intentos</th><th>Acciones</th></tr></thead><tbody>{rows.map(p=><tr key={p.studentId}><th>{p.studentCode}</th><td>{p.enabled?'Habilitado':'Deshabilitado'}</td><td>{p.createdAt}</td><td>{p.lastLoginAt??'Sin acceso'}</td><td>{p.attemptCount}</td><td><button disabled={busy} onClick={()=>{if(window.confirm(`¿Resetear la clave de ${p.studentCode}? Se invalidarán sus sesiones anteriores.`))void action(`/${p.studentId}/reset-password`,'POST');}}>Resetear clave</button><button disabled={busy} onClick={()=>{void action(`/${p.studentId}`,'PATCH',{enabled:!p.enabled});}}>{p.enabled?'Deshabilitar':'Habilitar'}</button></td></tr>)}</tbody></table></div>{rows.length===0&&<p>No hay participantes en esta página.</p>}<div className="meta-pager"><button disabled={busy||page===0} onClick={()=>{setIssued(null);setPage(p=>p-1);}}>Anterior</button><span>Página {page+1}</span><button disabled={busy||rows.length<20} onClick={()=>{setIssued(null);setPage(p=>p+1);}}>Siguiente</button></div></section>;
}
