export interface Page<T> { items: T[]; page: number; size: number; total: number }
export interface Capabilities { canViewStudentModel: boolean; canViewRules: boolean; canViewParameters: boolean; canViewTrace: boolean; canMutateRules: boolean; canMutateParameters: boolean; canReviewProposals: boolean }
export interface StudentSummary { studentId: string; createdAt: string; lastInteraction: string; attemptCount: number; completedConceptCount: number }
export interface Mastery { conceptId: string; masteryScore: number; attemptCount: number; successCount: number; failureCount: number; consecutiveFailures: number; averageResolutionTime: number; hintCount: number; recentErrorPatterns: string[]; lastUpdated: string }
export interface Overview { studentId: string; modelVersion: number; lastUpdated: string; conceptMasteries: Mastery[]; concepts: {conceptId: string; name: string; masteryThreshold: number; prerequisites: string[]}[]; progress: {levels: {levelId: string; conceptId: string; completed: boolean; unlocked: boolean; masteryScore: number; attemptCount: number}[]} }
export interface Attempt { attemptId: string; activityId: string; conceptId: string; submittedAt: string; functionalPassed: boolean; activityPassed: boolean; patterns: string[]; timelineUrl: string }
export type ActionType = 'SHOW_HINT' | 'CHANGE_HINT_LEVEL' | 'REPEAT_ACTIVITY' | 'SELECT_REINFORCEMENT_ACTIVITY' | 'ADVANCE_TO_NEXT_CONCEPT' | 'INCREASE_DIFFICULTY' | 'DECREASE_DIFFICULTY' | 'SHOW_CODE_VIEW' | 'HIDE_CODE_VIEW' | 'CHANGE_FEEDBACK_STYLE';
export interface Action { type: ActionType; hintLevel: 'CONCEPTUAL' | 'GUIDED' | 'DIRECT' | null; feedbackStyle: 'CONCISE' | 'EXPLANATORY' | null; targetConceptId: string | null }
export interface Rule { ruleId: string; name: string | null; version: number; priority: number; eventType: string; conditionSummary: string; actions: Action[]; enabled: boolean }
export interface Rules { source: string; rulesetVersion: number; rulesetHash: string; rules: Rule[] }
export interface ParameterValues { version: number; hintLevel: string; difficultyAdjustmentEnabled: boolean; routeAdaptationEnabled: boolean; feedbackDetail: string; failureThreshold: number; successThreshold: number; masteryThreshold: number; maxHintsPerActivity: number; maxAttemptsBeforeReinforcement: number }
export interface Parameters { source: string; parametersVersion: number; parametersHash: string; values: ParameterValues }
export interface RuleAudit { ruleId: string; version: number; priority: number; specificity: number; severity: string; sourceOrder: number; status: string; reasonCode: string; evidence: {attribute: string; operator: string; observed: string; expected: string; matched: boolean}[] }
export interface Decision { decisionId: string; studentId: string; attemptId: string; createdAt: string; rulesetVersion: number; parametersVersion: number; rulesEvaluated: number; rulesMatched: string[]; selectedRule: string | null; contributingRules: string[]; discardedRules: RuleAudit[]; actions: Action[]; explanation: {selectedRule: string | null; reason: string; reasonCodes: string[]; evidence: string[]}; ruleAudit: RuleAudit[]; actionAudit: {ruleId: string; sourceActionOrder: number; action: Action; status: string; reasonCode: string}[]; contextHash: string; rulesetHash: string; parametersHash: string; decisionFingerprint: string; llmUsed: boolean; llmPurpose: string | null }
export interface Adaptation { activityId: string; conceptId: string; decision: Decision }
export interface Feedback { feedbackId: string; attemptId: string; adaptationDecisionId: string | null; purpose: string; message: string; question: string | null; focus: string | null; hintStage: string; language: string; source: 'OPENAI' | 'GEMINI' | 'FAKE' | 'FALLBACK'; provider: 'OPENAI' | 'GEMINI' | 'FAKE' | 'DISABLED'; model: string | null; llmUsed: boolean; fallbackReason: string | null; promptTemplateVersion: number; policyVersion: number; promptHash: string; sanitizedContextHash: string; createdAt: string }
export interface UiAudit { configurationVersion: number; configurationFingerprint: string; hintPanelMode: string; navigationMode: string; difficultyMode: string; tutorMode: string; showCodePanel: boolean; safeDefault: boolean }
export type EventType = 'SESSION_STARTED' | 'SESSION_ENDED' | 'ACTIVITY_OPENED' | 'NAVIGATION_PRESENTED' | 'ATTEMPT_CREATED' | 'PROGRAM_MODEL_CREATED' | 'PROGRAM_MODEL_VALIDATED' | 'EXECUTION_STARTED' | 'EXECUTION_COMPLETED' | 'EVALUATION_COMPLETED' | 'ERROR_PATTERN_DETECTED' | 'STUDENT_MODEL_UPDATED' | 'ADAPTATION_STARTED' | 'ADAPTATION_COMPLETED' | 'FEEDBACK_REQUESTED' | 'FEEDBACK_CLASSIFICATION_COMPLETED' | 'FEEDBACK_GENERATED' | 'FEEDBACK_FALLBACK_USED' | 'UI_CONFIGURATION_CREATED' | 'ACTIVITY_COMPLETED' | 'TECHNICAL_ERROR';
export type Payload = {status: string} | {activityId: string; conceptId: string} | {activityId: string; navigationMode: string; configurationFingerprint: string} | {programHash: string; metamodelVersion: string; statementCount: number; valid: boolean | null} | {success: boolean; status: string; steps: number; goalReached: boolean; errorCount: number; traceHash: string} | {evaluationVersion: number; functionalPassed: boolean; structuralPassed: boolean; activityPassed: boolean; requiredConceptUsed: boolean; patternCount: number} | {patternId: string; severity: string; conceptId: string} | {conceptId: string; masteryBefore: number; masteryDelta: number; masteryAfter: number; attemptCount: number; successCount: number; failureCount: number; consecutiveFailures: number; policyVersion: number} | {decisionId: string; decisionFingerprint: string; rulesetVersion: number; rulesetHash: string; parametersVersion: number; parametersHash: string; selectedRule: string | null; contributingRuleCount: number; discardedRuleCount: number; actionTypes: string[]; contextHash: string} | {feedbackId: string; provider: string; model: string | null; source: string; llmUsed: boolean; fallbackReason: string | null; purpose: string; promptTemplateVersion: number; policyVersion: number; promptHash: string; sanitizedContextHash: string; providerCallCount: number} | {feedbackId: string; status: string; attempts: number; validationReason: string | null} | UiAudit | {errorCode: string; component: string};
export interface AuditEvent { id: string; attemptId: string | null; sessionId: string | null; studentId: string; requestId: string; sequence: number; type: EventType; source: 'BACKEND' | 'EXECUTION' | 'EVALUATION' | 'LEARNING' | 'ADAPTATION' | 'LLM' | 'UI' | 'SYSTEM'; eventVersion: number; occurredAt: string; payload: Payload | null; payloadHash: string }
export interface Timeline { studentId: string; attemptId: string; sessionId: string | null; startedAt: string; completedAt: string; traceStatus: 'COMPLETE' | 'PARTIAL' | 'INCONSISTENT'; gaps: string[]; attempt: {activityId: string; conceptId: string; functionalPassed: boolean; activityPassed: boolean; masteryBefore: number; masteryDelta: number; masteryAfter: number; policyVersion: number; patterns: string[]; programHash: string | null}; events: AuditEvent[]; activityOpenEvents: AuditEvent[]; adaptation: Decision | null; feedback: Feedback[]; uiConfigurations: UiAudit[] }
