/*
 * generated by Xtext
 */
package com.project.mde.adaptation.dsl.serializer;

import com.google.inject.Inject;
import com.project.mde.adaptation.AdaptationPackage;
import com.project.mde.adaptation.AdaptationParameters;
import com.project.mde.adaptation.AdaptationRule;
import com.project.mde.adaptation.AdaptationRuleSet;
import com.project.mde.adaptation.BooleanValue;
import com.project.mde.adaptation.ComparisonCondition;
import com.project.mde.adaptation.DecimalValue;
import com.project.mde.adaptation.Event;
import com.project.mde.adaptation.IntegerValue;
import com.project.mde.adaptation.LogicalCondition;
import com.project.mde.adaptation.NotCondition;
import com.project.mde.adaptation.StringValue;
import com.project.mde.adaptation.dsl.services.AdaptationRulesGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class AdaptationRulesSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private AdaptationRulesGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == AdaptationPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case AdaptationPackage.ACTION:
				sequence_Action(context, (com.project.mde.adaptation.Action) semanticObject); 
				return; 
			case AdaptationPackage.ADAPTATION_PARAMETERS:
				sequence_AdaptationParameters(context, (AdaptationParameters) semanticObject); 
				return; 
			case AdaptationPackage.ADAPTATION_RULE:
				sequence_AdaptationRule(context, (AdaptationRule) semanticObject); 
				return; 
			case AdaptationPackage.ADAPTATION_RULE_SET:
				sequence_AdaptationRuleSet(context, (AdaptationRuleSet) semanticObject); 
				return; 
			case AdaptationPackage.BOOLEAN_VALUE:
				sequence_BooleanValue(context, (BooleanValue) semanticObject); 
				return; 
			case AdaptationPackage.COMPARISON_CONDITION:
				sequence_ComparisonCondition(context, (ComparisonCondition) semanticObject); 
				return; 
			case AdaptationPackage.DECIMAL_VALUE:
				sequence_DecimalValue(context, (DecimalValue) semanticObject); 
				return; 
			case AdaptationPackage.EVENT:
				sequence_Event(context, (Event) semanticObject); 
				return; 
			case AdaptationPackage.INTEGER_VALUE:
				sequence_IntegerValue(context, (IntegerValue) semanticObject); 
				return; 
			case AdaptationPackage.LOGICAL_CONDITION:
				sequence_AndCondition_OrCondition(context, (LogicalCondition) semanticObject); 
				return; 
			case AdaptationPackage.NOT_CONDITION:
				sequence_UnaryCondition(context, (NotCondition) semanticObject); 
				return; 
			case AdaptationPackage.STRING_VALUE:
				sequence_StringValue(context, (StringValue) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Action returns Action
	 *
	 * Constraint:
	 *     (type=ActionType parameters=AdaptationParameters?)
	 * </pre>
	 */
	protected void sequence_Action(ISerializationContext context, com.project.mde.adaptation.Action semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AdaptationParameters returns AdaptationParameters
	 *
	 * Constraint:
	 *     ((hintLevel=HintLevel feedbackStyle=FeedbackStyle?) | (feedbackStyle=FeedbackStyle hintLevel=HintLevel?))
	 * </pre>
	 */
	protected void sequence_AdaptationParameters(ISerializationContext context, AdaptationParameters semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AdaptationRuleSet returns AdaptationRuleSet
	 *
	 * Constraint:
	 *     (name=STRING version=SignedInt rules+=AdaptationRule*)
	 * </pre>
	 */
	protected void sequence_AdaptationRuleSet(ISerializationContext context, AdaptationRuleSet semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AdaptationRule returns AdaptationRule
	 *
	 * Constraint:
	 *     (
	 *         id=ID 
	 *         name=STRING? 
	 *         version=SignedInt 
	 *         enabled=Boolean 
	 *         event=Event 
	 *         condition=Condition? 
	 *         actions+=Action* 
	 *         priority=SignedInt
	 *     )
	 * </pre>
	 */
	protected void sequence_AdaptationRule(ISerializationContext context, AdaptationRule semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Condition returns LogicalCondition
	 *     OrCondition returns LogicalCondition
	 *     OrCondition.LogicalCondition_1_0 returns LogicalCondition
	 *     AndCondition returns LogicalCondition
	 *     AndCondition.LogicalCondition_1_0 returns LogicalCondition
	 *     UnaryCondition returns LogicalCondition
	 *
	 * Constraint:
	 *     (
	 *         (left=OrCondition_LogicalCondition_1_0 operator=Or right=AndCondition) | 
	 *         (left=AndCondition_LogicalCondition_1_0 operator=And right=UnaryCondition)
	 *     )
	 * </pre>
	 */
	protected void sequence_AndCondition_OrCondition(ISerializationContext context, LogicalCondition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Value returns BooleanValue
	 *     BooleanValue returns BooleanValue
	 *
	 * Constraint:
	 *     value=Boolean
	 * </pre>
	 */
	protected void sequence_BooleanValue(ISerializationContext context, BooleanValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, AdaptationPackage.Literals.BOOLEAN_VALUE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AdaptationPackage.Literals.BOOLEAN_VALUE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getBooleanValueAccess().getValueBooleanParserRuleCall_0(), semanticObject.isValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Condition returns ComparisonCondition
	 *     OrCondition returns ComparisonCondition
	 *     OrCondition.LogicalCondition_1_0 returns ComparisonCondition
	 *     AndCondition returns ComparisonCondition
	 *     AndCondition.LogicalCondition_1_0 returns ComparisonCondition
	 *     UnaryCondition returns ComparisonCondition
	 *     ComparisonCondition returns ComparisonCondition
	 *
	 * Constraint:
	 *     (attribute=ID operator=ComparisonOperator value=Value)
	 * </pre>
	 */
	protected void sequence_ComparisonCondition(ISerializationContext context, ComparisonCondition semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, AdaptationPackage.Literals.COMPARISON_CONDITION__ATTRIBUTE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AdaptationPackage.Literals.COMPARISON_CONDITION__ATTRIBUTE));
			if (transientValues.isValueTransient(semanticObject, AdaptationPackage.Literals.COMPARISON_CONDITION__OPERATOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AdaptationPackage.Literals.COMPARISON_CONDITION__OPERATOR));
			if (transientValues.isValueTransient(semanticObject, AdaptationPackage.Literals.COMPARISON_CONDITION__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AdaptationPackage.Literals.COMPARISON_CONDITION__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getComparisonConditionAccess().getAttributeIDTerminalRuleCall_0_0(), semanticObject.getAttribute());
		feeder.accept(grammarAccess.getComparisonConditionAccess().getOperatorComparisonOperatorEnumRuleCall_1_0(), semanticObject.getOperator());
		feeder.accept(grammarAccess.getComparisonConditionAccess().getValueValueParserRuleCall_2_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Value returns DecimalValue
	 *     DecimalValue returns DecimalValue
	 *
	 * Constraint:
	 *     value=Decimal
	 * </pre>
	 */
	protected void sequence_DecimalValue(ISerializationContext context, DecimalValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, AdaptationPackage.Literals.DECIMAL_VALUE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AdaptationPackage.Literals.DECIMAL_VALUE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDecimalValueAccess().getValueDecimalParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Event returns Event
	 *
	 * Constraint:
	 *     type=EventType
	 * </pre>
	 */
	protected void sequence_Event(ISerializationContext context, Event semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, AdaptationPackage.Literals.EVENT__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AdaptationPackage.Literals.EVENT__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEventAccess().getTypeEventTypeEnumRuleCall_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Value returns IntegerValue
	 *     IntegerValue returns IntegerValue
	 *
	 * Constraint:
	 *     value=Long
	 * </pre>
	 */
	protected void sequence_IntegerValue(ISerializationContext context, IntegerValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, AdaptationPackage.Literals.INTEGER_VALUE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AdaptationPackage.Literals.INTEGER_VALUE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIntegerValueAccess().getValueLongParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Value returns StringValue
	 *     StringValue returns StringValue
	 *
	 * Constraint:
	 *     value=STRING
	 * </pre>
	 */
	protected void sequence_StringValue(ISerializationContext context, StringValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, AdaptationPackage.Literals.STRING_VALUE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AdaptationPackage.Literals.STRING_VALUE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getStringValueAccess().getValueSTRINGTerminalRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Condition returns NotCondition
	 *     OrCondition returns NotCondition
	 *     OrCondition.LogicalCondition_1_0 returns NotCondition
	 *     AndCondition returns NotCondition
	 *     AndCondition.LogicalCondition_1_0 returns NotCondition
	 *     UnaryCondition returns NotCondition
	 *
	 * Constraint:
	 *     operand=UnaryCondition
	 * </pre>
	 */
	protected void sequence_UnaryCondition(ISerializationContext context, NotCondition semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, AdaptationPackage.Literals.NOT_CONDITION__OPERAND) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AdaptationPackage.Literals.NOT_CONDITION__OPERAND));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getUnaryConditionAccess().getOperandUnaryConditionParserRuleCall_0_2_0(), semanticObject.getOperand());
		feeder.finish();
	}
	
	
}
