/*
 * generated by Xtext
 */
grammar InternalAdaptationRules;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package com.project.mde.adaptation.dsl.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package com.project.mde.adaptation.dsl.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.common.util.Enumerator;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import com.project.mde.adaptation.dsl.services.AdaptationRulesGrammarAccess;

}

@parser::members {

 	private AdaptationRulesGrammarAccess grammarAccess;

    public InternalAdaptationRulesParser(TokenStream input, AdaptationRulesGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "AdaptationRuleSet";
   	}

   	@Override
   	protected AdaptationRulesGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleAdaptationRuleSet
entryRuleAdaptationRuleSet returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAdaptationRuleSetRule()); }
	iv_ruleAdaptationRuleSet=ruleAdaptationRuleSet
	{ $current=$iv_ruleAdaptationRuleSet.current; }
	EOF;

// Rule AdaptationRuleSet
ruleAdaptationRuleSet returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='ruleset'
		{
			newLeafNode(otherlv_0, grammarAccess.getAdaptationRuleSetAccess().getRulesetKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_STRING
				{
					newLeafNode(lv_name_1_0, grammarAccess.getAdaptationRuleSetAccess().getNameSTRINGTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getAdaptationRuleSetRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_2='version'
		{
			newLeafNode(otherlv_2, grammarAccess.getAdaptationRuleSetAccess().getVersionKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAdaptationRuleSetAccess().getVersionSignedIntParserRuleCall_3_0());
				}
				lv_version_3_0=ruleSignedInt
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAdaptationRuleSetRule());
					}
					set(
						$current,
						"version",
						lv_version_3_0,
						"com.project.mde.adaptation.dsl.AdaptationRules.SignedInt");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getAdaptationRuleSetAccess().getRulesAdaptationRuleParserRuleCall_4_0());
				}
				lv_rules_4_0=ruleAdaptationRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAdaptationRuleSetRule());
					}
					add(
						$current,
						"rules",
						lv_rules_4_0,
						"com.project.mde.adaptation.dsl.AdaptationRules.AdaptationRule");
					afterParserOrEnumRuleCall();
				}
			)
		)*
	)
;

// Entry rule entryRuleAdaptationRule
entryRuleAdaptationRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAdaptationRuleRule()); }
	iv_ruleAdaptationRule=ruleAdaptationRule
	{ $current=$iv_ruleAdaptationRule.current; }
	EOF;

// Rule AdaptationRule
ruleAdaptationRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='rule'
		{
			newLeafNode(otherlv_0, grammarAccess.getAdaptationRuleAccess().getRuleKeyword_0());
		}
		(
			(
				lv_id_1_0=RULE_ID
				{
					newLeafNode(lv_id_1_0, grammarAccess.getAdaptationRuleAccess().getIdIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getAdaptationRuleRule());
					}
					setWithLastConsumed(
						$current,
						"id",
						lv_id_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		(
			otherlv_2='name'
			{
				newLeafNode(otherlv_2, grammarAccess.getAdaptationRuleAccess().getNameKeyword_2_0());
			}
			(
				(
					lv_name_3_0=RULE_STRING
					{
						newLeafNode(lv_name_3_0, grammarAccess.getAdaptationRuleAccess().getNameSTRINGTerminalRuleCall_2_1_0());
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getAdaptationRuleRule());
						}
						setWithLastConsumed(
							$current,
							"name",
							lv_name_3_0,
							"org.eclipse.xtext.common.Terminals.STRING");
					}
				)
			)
		)?
		otherlv_4='version'
		{
			newLeafNode(otherlv_4, grammarAccess.getAdaptationRuleAccess().getVersionKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAdaptationRuleAccess().getVersionSignedIntParserRuleCall_4_0());
				}
				lv_version_5_0=ruleSignedInt
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAdaptationRuleRule());
					}
					set(
						$current,
						"version",
						lv_version_5_0,
						"com.project.mde.adaptation.dsl.AdaptationRules.SignedInt");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_6='enabled'
		{
			newLeafNode(otherlv_6, grammarAccess.getAdaptationRuleAccess().getEnabledKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAdaptationRuleAccess().getEnabledBooleanParserRuleCall_6_0());
				}
				lv_enabled_7_0=ruleBoolean
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAdaptationRuleRule());
					}
					set(
						$current,
						"enabled",
						lv_enabled_7_0,
						"com.project.mde.adaptation.dsl.AdaptationRules.Boolean");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_8='on'
		{
			newLeafNode(otherlv_8, grammarAccess.getAdaptationRuleAccess().getOnKeyword_7());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAdaptationRuleAccess().getEventEventParserRuleCall_8_0());
				}
				lv_event_9_0=ruleEvent
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAdaptationRuleRule());
					}
					set(
						$current,
						"event",
						lv_event_9_0,
						"com.project.mde.adaptation.dsl.AdaptationRules.Event");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_10='when'
		{
			newLeafNode(otherlv_10, grammarAccess.getAdaptationRuleAccess().getWhenKeyword_9());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAdaptationRuleAccess().getConditionConditionParserRuleCall_10_0());
				}
				lv_condition_11_0=ruleCondition
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAdaptationRuleRule());
					}
					set(
						$current,
						"condition",
						lv_condition_11_0,
						"com.project.mde.adaptation.dsl.AdaptationRules.Condition");
					afterParserOrEnumRuleCall();
				}
			)
		)?
		otherlv_12='then'
		{
			newLeafNode(otherlv_12, grammarAccess.getAdaptationRuleAccess().getThenKeyword_11());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAdaptationRuleAccess().getActionsActionParserRuleCall_12_0());
				}
				lv_actions_13_0=ruleAction
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAdaptationRuleRule());
					}
					add(
						$current,
						"actions",
						lv_actions_13_0,
						"com.project.mde.adaptation.dsl.AdaptationRules.Action");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_14='priority'
		{
			newLeafNode(otherlv_14, grammarAccess.getAdaptationRuleAccess().getPriorityKeyword_13());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAdaptationRuleAccess().getPrioritySignedIntParserRuleCall_14_0());
				}
				lv_priority_15_0=ruleSignedInt
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAdaptationRuleRule());
					}
					set(
						$current,
						"priority",
						lv_priority_15_0,
						"com.project.mde.adaptation.dsl.AdaptationRules.SignedInt");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleEvent
entryRuleEvent returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getEventRule()); }
	iv_ruleEvent=ruleEvent
	{ $current=$iv_ruleEvent.current; }
	EOF;

// Rule Event
ruleEvent returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getEventAccess().getTypeEventTypeEnumRuleCall_0());
			}
			lv_type_0_0=ruleEventType
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getEventRule());
				}
				set(
					$current,
					"type",
					lv_type_0_0,
					"com.project.mde.adaptation.dsl.AdaptationRules.EventType");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleCondition
entryRuleCondition returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getConditionRule()); }
	iv_ruleCondition=ruleCondition
	{ $current=$iv_ruleCondition.current; }
	EOF;

// Rule Condition
ruleCondition returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	{
		newCompositeNode(grammarAccess.getConditionAccess().getOrConditionParserRuleCall());
	}
	this_OrCondition_0=ruleOrCondition
	{
		$current = $this_OrCondition_0.current;
		afterParserOrEnumRuleCall();
	}
;

// Entry rule entryRuleOrCondition
entryRuleOrCondition returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getOrConditionRule()); }
	iv_ruleOrCondition=ruleOrCondition
	{ $current=$iv_ruleOrCondition.current; }
	EOF;

// Rule OrCondition
ruleOrCondition returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getOrConditionAccess().getAndConditionParserRuleCall_0());
		}
		this_AndCondition_0=ruleAndCondition
		{
			$current = $this_AndCondition_0.current;
			afterParserOrEnumRuleCall();
		}
		(
			(
				{
					$current = forceCreateModelElementAndSet(
						grammarAccess.getOrConditionAccess().getLogicalConditionLeftAction_1_0(),
						$current);
				}
			)
			(
				(
					{
						newCompositeNode(grammarAccess.getOrConditionAccess().getOperatorOrEnumRuleCall_1_1_0());
					}
					lv_operator_2_0=ruleOr
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getOrConditionRule());
						}
						set(
							$current,
							"operator",
							lv_operator_2_0,
							"com.project.mde.adaptation.dsl.AdaptationRules.Or");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				(
					{
						newCompositeNode(grammarAccess.getOrConditionAccess().getRightAndConditionParserRuleCall_1_2_0());
					}
					lv_right_3_0=ruleAndCondition
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getOrConditionRule());
						}
						set(
							$current,
							"right",
							lv_right_3_0,
							"com.project.mde.adaptation.dsl.AdaptationRules.AndCondition");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
	)
;

// Entry rule entryRuleAndCondition
entryRuleAndCondition returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAndConditionRule()); }
	iv_ruleAndCondition=ruleAndCondition
	{ $current=$iv_ruleAndCondition.current; }
	EOF;

// Rule AndCondition
ruleAndCondition returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getAndConditionAccess().getUnaryConditionParserRuleCall_0());
		}
		this_UnaryCondition_0=ruleUnaryCondition
		{
			$current = $this_UnaryCondition_0.current;
			afterParserOrEnumRuleCall();
		}
		(
			(
				{
					$current = forceCreateModelElementAndSet(
						grammarAccess.getAndConditionAccess().getLogicalConditionLeftAction_1_0(),
						$current);
				}
			)
			(
				(
					{
						newCompositeNode(grammarAccess.getAndConditionAccess().getOperatorAndEnumRuleCall_1_1_0());
					}
					lv_operator_2_0=ruleAnd
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getAndConditionRule());
						}
						set(
							$current,
							"operator",
							lv_operator_2_0,
							"com.project.mde.adaptation.dsl.AdaptationRules.And");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				(
					{
						newCompositeNode(grammarAccess.getAndConditionAccess().getRightUnaryConditionParserRuleCall_1_2_0());
					}
					lv_right_3_0=ruleUnaryCondition
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getAndConditionRule());
						}
						set(
							$current,
							"right",
							lv_right_3_0,
							"com.project.mde.adaptation.dsl.AdaptationRules.UnaryCondition");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
	)
;

// Entry rule entryRuleUnaryCondition
entryRuleUnaryCondition returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getUnaryConditionRule()); }
	iv_ruleUnaryCondition=ruleUnaryCondition
	{ $current=$iv_ruleUnaryCondition.current; }
	EOF;

// Rule UnaryCondition
ruleUnaryCondition returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					$current = forceCreateModelElement(
						grammarAccess.getUnaryConditionAccess().getNotConditionAction_0_0(),
						$current);
				}
			)
			otherlv_1='not'
			{
				newLeafNode(otherlv_1, grammarAccess.getUnaryConditionAccess().getNotKeyword_0_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getUnaryConditionAccess().getOperandUnaryConditionParserRuleCall_0_2_0());
					}
					lv_operand_2_0=ruleUnaryCondition
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getUnaryConditionRule());
						}
						set(
							$current,
							"operand",
							lv_operand_2_0,
							"com.project.mde.adaptation.dsl.AdaptationRules.UnaryCondition");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)
		    |
		(
			otherlv_3='('
			{
				newLeafNode(otherlv_3, grammarAccess.getUnaryConditionAccess().getLeftParenthesisKeyword_1_0());
			}
			{
				newCompositeNode(grammarAccess.getUnaryConditionAccess().getConditionParserRuleCall_1_1());
			}
			this_Condition_4=ruleCondition
			{
				$current = $this_Condition_4.current;
				afterParserOrEnumRuleCall();
			}
			otherlv_5=')'
			{
				newLeafNode(otherlv_5, grammarAccess.getUnaryConditionAccess().getRightParenthesisKeyword_1_2());
			}
		)
		    |
		{
			newCompositeNode(grammarAccess.getUnaryConditionAccess().getComparisonConditionParserRuleCall_2());
		}
		this_ComparisonCondition_6=ruleComparisonCondition
		{
			$current = $this_ComparisonCondition_6.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleComparisonCondition
entryRuleComparisonCondition returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getComparisonConditionRule()); }
	iv_ruleComparisonCondition=ruleComparisonCondition
	{ $current=$iv_ruleComparisonCondition.current; }
	EOF;

// Rule ComparisonCondition
ruleComparisonCondition returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_attribute_0_0=RULE_ID
				{
					newLeafNode(lv_attribute_0_0, grammarAccess.getComparisonConditionAccess().getAttributeIDTerminalRuleCall_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getComparisonConditionRule());
					}
					setWithLastConsumed(
						$current,
						"attribute",
						lv_attribute_0_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getComparisonConditionAccess().getOperatorComparisonOperatorEnumRuleCall_1_0());
				}
				lv_operator_1_0=ruleComparisonOperator
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getComparisonConditionRule());
					}
					set(
						$current,
						"operator",
						lv_operator_1_0,
						"com.project.mde.adaptation.dsl.AdaptationRules.ComparisonOperator");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getComparisonConditionAccess().getValueValueParserRuleCall_2_0());
				}
				lv_value_2_0=ruleValue
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getComparisonConditionRule());
					}
					set(
						$current,
						"value",
						lv_value_2_0,
						"com.project.mde.adaptation.dsl.AdaptationRules.Value");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleValue
entryRuleValue returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getValueRule()); }
	iv_ruleValue=ruleValue
	{ $current=$iv_ruleValue.current; }
	EOF;

// Rule Value
ruleValue returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getValueAccess().getStringValueParserRuleCall_0());
		}
		this_StringValue_0=ruleStringValue
		{
			$current = $this_StringValue_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getValueAccess().getDecimalValueParserRuleCall_1());
		}
		this_DecimalValue_1=ruleDecimalValue
		{
			$current = $this_DecimalValue_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getValueAccess().getIntegerValueParserRuleCall_2());
		}
		this_IntegerValue_2=ruleIntegerValue
		{
			$current = $this_IntegerValue_2.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getValueAccess().getBooleanValueParserRuleCall_3());
		}
		this_BooleanValue_3=ruleBooleanValue
		{
			$current = $this_BooleanValue_3.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleStringValue
entryRuleStringValue returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getStringValueRule()); }
	iv_ruleStringValue=ruleStringValue
	{ $current=$iv_ruleStringValue.current; }
	EOF;

// Rule StringValue
ruleStringValue returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			lv_value_0_0=RULE_STRING
			{
				newLeafNode(lv_value_0_0, grammarAccess.getStringValueAccess().getValueSTRINGTerminalRuleCall_0());
			}
			{
				if ($current==null) {
					$current = createModelElement(grammarAccess.getStringValueRule());
				}
				setWithLastConsumed(
					$current,
					"value",
					lv_value_0_0,
					"org.eclipse.xtext.common.Terminals.STRING");
			}
		)
	)
;

// Entry rule entryRuleDecimalValue
entryRuleDecimalValue returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getDecimalValueRule()); }
	iv_ruleDecimalValue=ruleDecimalValue
	{ $current=$iv_ruleDecimalValue.current; }
	EOF;

// Rule DecimalValue
ruleDecimalValue returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getDecimalValueAccess().getValueDecimalParserRuleCall_0());
			}
			lv_value_0_0=ruleDecimal
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getDecimalValueRule());
				}
				set(
					$current,
					"value",
					lv_value_0_0,
					"com.project.mde.adaptation.dsl.AdaptationRules.Decimal");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleIntegerValue
entryRuleIntegerValue returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getIntegerValueRule()); }
	iv_ruleIntegerValue=ruleIntegerValue
	{ $current=$iv_ruleIntegerValue.current; }
	EOF;

// Rule IntegerValue
ruleIntegerValue returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getIntegerValueAccess().getValueLongParserRuleCall_0());
			}
			lv_value_0_0=ruleLong
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getIntegerValueRule());
				}
				set(
					$current,
					"value",
					lv_value_0_0,
					"com.project.mde.adaptation.dsl.AdaptationRules.Long");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleBooleanValue
entryRuleBooleanValue returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getBooleanValueRule()); }
	iv_ruleBooleanValue=ruleBooleanValue
	{ $current=$iv_ruleBooleanValue.current; }
	EOF;

// Rule BooleanValue
ruleBooleanValue returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getBooleanValueAccess().getValueBooleanParserRuleCall_0());
			}
			lv_value_0_0=ruleBoolean
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getBooleanValueRule());
				}
				set(
					$current,
					"value",
					lv_value_0_0,
					"com.project.mde.adaptation.dsl.AdaptationRules.Boolean");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleSignedInt
entryRuleSignedInt returns [String current=null]:
	{ newCompositeNode(grammarAccess.getSignedIntRule()); }
	iv_ruleSignedInt=ruleSignedInt
	{ $current=$iv_ruleSignedInt.current.getText(); }
	EOF;

// Rule SignedInt
ruleSignedInt returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			kw='-'
			{
				$current.merge(kw);
				newLeafNode(kw, grammarAccess.getSignedIntAccess().getHyphenMinusKeyword_0());
			}
		)?
		this_INT_1=RULE_INT
		{
			$current.merge(this_INT_1);
		}
		{
			newLeafNode(this_INT_1, grammarAccess.getSignedIntAccess().getINTTerminalRuleCall_1());
		}
	)
;

// Entry rule entryRuleLong
entryRuleLong returns [String current=null]:
	{ newCompositeNode(grammarAccess.getLongRule()); }
	iv_ruleLong=ruleLong
	{ $current=$iv_ruleLong.current.getText(); }
	EOF;

// Rule Long
ruleLong returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			kw='-'
			{
				$current.merge(kw);
				newLeafNode(kw, grammarAccess.getLongAccess().getHyphenMinusKeyword_0());
			}
		)?
		this_INT_1=RULE_INT
		{
			$current.merge(this_INT_1);
		}
		{
			newLeafNode(this_INT_1, grammarAccess.getLongAccess().getINTTerminalRuleCall_1());
		}
	)
;

// Entry rule entryRuleDecimal
entryRuleDecimal returns [String current=null]:
	{ newCompositeNode(grammarAccess.getDecimalRule()); }
	iv_ruleDecimal=ruleDecimal
	{ $current=$iv_ruleDecimal.current.getText(); }
	EOF;

// Rule Decimal
ruleDecimal returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			kw='-'
			{
				$current.merge(kw);
				newLeafNode(kw, grammarAccess.getDecimalAccess().getHyphenMinusKeyword_0());
			}
		)?
		this_INT_1=RULE_INT
		{
			$current.merge(this_INT_1);
		}
		{
			newLeafNode(this_INT_1, grammarAccess.getDecimalAccess().getINTTerminalRuleCall_1());
		}
		kw='.'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getDecimalAccess().getFullStopKeyword_2());
		}
		this_INT_3=RULE_INT
		{
			$current.merge(this_INT_3);
		}
		{
			newLeafNode(this_INT_3, grammarAccess.getDecimalAccess().getINTTerminalRuleCall_3());
		}
	)
;

// Entry rule entryRuleBoolean
entryRuleBoolean returns [String current=null]:
	{ newCompositeNode(grammarAccess.getBooleanRule()); }
	iv_ruleBoolean=ruleBoolean
	{ $current=$iv_ruleBoolean.current.getText(); }
	EOF;

// Rule Boolean
ruleBoolean returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		kw='true'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getBooleanAccess().getTrueKeyword_0());
		}
		    |
		kw='false'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getBooleanAccess().getFalseKeyword_1());
		}
	)
;

// Entry rule entryRuleAction
entryRuleAction returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getActionRule()); }
	iv_ruleAction=ruleAction
	{ $current=$iv_ruleAction.current; }
	EOF;

// Rule Action
ruleAction returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='action'
		{
			newLeafNode(otherlv_0, grammarAccess.getActionAccess().getActionKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getActionAccess().getTypeActionTypeEnumRuleCall_1_0());
				}
				lv_type_1_0=ruleActionType
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getActionRule());
					}
					set(
						$current,
						"type",
						lv_type_1_0,
						"com.project.mde.adaptation.dsl.AdaptationRules.ActionType");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getActionAccess().getParametersAdaptationParametersParserRuleCall_2_0());
				}
				lv_parameters_2_0=ruleAdaptationParameters
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getActionRule());
					}
					set(
						$current,
						"parameters",
						lv_parameters_2_0,
						"com.project.mde.adaptation.dsl.AdaptationRules.AdaptationParameters");
					afterParserOrEnumRuleCall();
				}
			)
		)?
	)
;

// Entry rule entryRuleAdaptationParameters
entryRuleAdaptationParameters returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAdaptationParametersRule()); }
	iv_ruleAdaptationParameters=ruleAdaptationParameters
	{ $current=$iv_ruleAdaptationParameters.current; }
	EOF;

// Rule AdaptationParameters
ruleAdaptationParameters returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			otherlv_0='level'
			{
				newLeafNode(otherlv_0, grammarAccess.getAdaptationParametersAccess().getLevelKeyword_0_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getAdaptationParametersAccess().getHintLevelHintLevelEnumRuleCall_0_1_0());
					}
					lv_hintLevel_1_0=ruleHintLevel
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getAdaptationParametersRule());
						}
						set(
							$current,
							"hintLevel",
							lv_hintLevel_1_0,
							"com.project.mde.adaptation.dsl.AdaptationRules.HintLevel");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_2='style'
				{
					newLeafNode(otherlv_2, grammarAccess.getAdaptationParametersAccess().getStyleKeyword_0_2_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getAdaptationParametersAccess().getFeedbackStyleFeedbackStyleEnumRuleCall_0_2_1_0());
						}
						lv_feedbackStyle_3_0=ruleFeedbackStyle
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getAdaptationParametersRule());
							}
							set(
								$current,
								"feedbackStyle",
								lv_feedbackStyle_3_0,
								"com.project.mde.adaptation.dsl.AdaptationRules.FeedbackStyle");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)?
		)
		    |
		(
			otherlv_4='style'
			{
				newLeafNode(otherlv_4, grammarAccess.getAdaptationParametersAccess().getStyleKeyword_1_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getAdaptationParametersAccess().getFeedbackStyleFeedbackStyleEnumRuleCall_1_1_0());
					}
					lv_feedbackStyle_5_0=ruleFeedbackStyle
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getAdaptationParametersRule());
						}
						set(
							$current,
							"feedbackStyle",
							lv_feedbackStyle_5_0,
							"com.project.mde.adaptation.dsl.AdaptationRules.FeedbackStyle");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_6='level'
				{
					newLeafNode(otherlv_6, grammarAccess.getAdaptationParametersAccess().getLevelKeyword_1_2_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getAdaptationParametersAccess().getHintLevelHintLevelEnumRuleCall_1_2_1_0());
						}
						lv_hintLevel_7_0=ruleHintLevel
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getAdaptationParametersRule());
							}
							set(
								$current,
								"hintLevel",
								lv_hintLevel_7_0,
								"com.project.mde.adaptation.dsl.AdaptationRules.HintLevel");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)?
		)
	)
;

// Rule EventType
ruleEventType returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		enumLiteral_0='ATTEMPT_EVALUATED'
		{
			$current = grammarAccess.getEventTypeAccess().getATTEMPT_EVALUATEDEnumLiteralDeclaration().getEnumLiteral().getInstance();
			newLeafNode(enumLiteral_0, grammarAccess.getEventTypeAccess().getATTEMPT_EVALUATEDEnumLiteralDeclaration());
		}
	)
;

// Rule Or
ruleOr returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		enumLiteral_0='or'
		{
			$current = grammarAccess.getOrAccess().getOREnumLiteralDeclaration().getEnumLiteral().getInstance();
			newLeafNode(enumLiteral_0, grammarAccess.getOrAccess().getOREnumLiteralDeclaration());
		}
	)
;

// Rule And
ruleAnd returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		enumLiteral_0='and'
		{
			$current = grammarAccess.getAndAccess().getANDEnumLiteralDeclaration().getEnumLiteral().getInstance();
			newLeafNode(enumLiteral_0, grammarAccess.getAndAccess().getANDEnumLiteralDeclaration());
		}
	)
;

// Rule ComparisonOperator
ruleComparisonOperator returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='=='
			{
				$current = grammarAccess.getComparisonOperatorAccess().getEQEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getComparisonOperatorAccess().getEQEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='!='
			{
				$current = grammarAccess.getComparisonOperatorAccess().getNEEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getComparisonOperatorAccess().getNEEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='>'
			{
				$current = grammarAccess.getComparisonOperatorAccess().getGTEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getComparisonOperatorAccess().getGTEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='>='
			{
				$current = grammarAccess.getComparisonOperatorAccess().getGEEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getComparisonOperatorAccess().getGEEnumLiteralDeclaration_3());
			}
		)
		    |
		(
			enumLiteral_4='<'
			{
				$current = grammarAccess.getComparisonOperatorAccess().getLTEnumLiteralDeclaration_4().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_4, grammarAccess.getComparisonOperatorAccess().getLTEnumLiteralDeclaration_4());
			}
		)
		    |
		(
			enumLiteral_5='<='
			{
				$current = grammarAccess.getComparisonOperatorAccess().getLEEnumLiteralDeclaration_5().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_5, grammarAccess.getComparisonOperatorAccess().getLEEnumLiteralDeclaration_5());
			}
		)
		    |
		(
			enumLiteral_6='contains'
			{
				$current = grammarAccess.getComparisonOperatorAccess().getCONTAINSEnumLiteralDeclaration_6().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_6, grammarAccess.getComparisonOperatorAccess().getCONTAINSEnumLiteralDeclaration_6());
			}
		)
	)
;

// Rule ActionType
ruleActionType returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='SHOW_HINT'
			{
				$current = grammarAccess.getActionTypeAccess().getSHOW_HINTEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getActionTypeAccess().getSHOW_HINTEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='CHANGE_HINT_LEVEL'
			{
				$current = grammarAccess.getActionTypeAccess().getCHANGE_HINT_LEVELEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getActionTypeAccess().getCHANGE_HINT_LEVELEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='REPEAT_ACTIVITY'
			{
				$current = grammarAccess.getActionTypeAccess().getREPEAT_ACTIVITYEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getActionTypeAccess().getREPEAT_ACTIVITYEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='SELECT_REINFORCEMENT_ACTIVITY'
			{
				$current = grammarAccess.getActionTypeAccess().getSELECT_REINFORCEMENT_ACTIVITYEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getActionTypeAccess().getSELECT_REINFORCEMENT_ACTIVITYEnumLiteralDeclaration_3());
			}
		)
		    |
		(
			enumLiteral_4='ADVANCE_TO_NEXT_CONCEPT'
			{
				$current = grammarAccess.getActionTypeAccess().getADVANCE_TO_NEXT_CONCEPTEnumLiteralDeclaration_4().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_4, grammarAccess.getActionTypeAccess().getADVANCE_TO_NEXT_CONCEPTEnumLiteralDeclaration_4());
			}
		)
		    |
		(
			enumLiteral_5='INCREASE_DIFFICULTY'
			{
				$current = grammarAccess.getActionTypeAccess().getINCREASE_DIFFICULTYEnumLiteralDeclaration_5().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_5, grammarAccess.getActionTypeAccess().getINCREASE_DIFFICULTYEnumLiteralDeclaration_5());
			}
		)
		    |
		(
			enumLiteral_6='DECREASE_DIFFICULTY'
			{
				$current = grammarAccess.getActionTypeAccess().getDECREASE_DIFFICULTYEnumLiteralDeclaration_6().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_6, grammarAccess.getActionTypeAccess().getDECREASE_DIFFICULTYEnumLiteralDeclaration_6());
			}
		)
		    |
		(
			enumLiteral_7='SHOW_CODE_VIEW'
			{
				$current = grammarAccess.getActionTypeAccess().getSHOW_CODE_VIEWEnumLiteralDeclaration_7().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_7, grammarAccess.getActionTypeAccess().getSHOW_CODE_VIEWEnumLiteralDeclaration_7());
			}
		)
		    |
		(
			enumLiteral_8='HIDE_CODE_VIEW'
			{
				$current = grammarAccess.getActionTypeAccess().getHIDE_CODE_VIEWEnumLiteralDeclaration_8().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_8, grammarAccess.getActionTypeAccess().getHIDE_CODE_VIEWEnumLiteralDeclaration_8());
			}
		)
		    |
		(
			enumLiteral_9='CHANGE_FEEDBACK_STYLE'
			{
				$current = grammarAccess.getActionTypeAccess().getCHANGE_FEEDBACK_STYLEEnumLiteralDeclaration_9().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_9, grammarAccess.getActionTypeAccess().getCHANGE_FEEDBACK_STYLEEnumLiteralDeclaration_9());
			}
		)
	)
;

// Rule HintLevel
ruleHintLevel returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='CONCEPTUAL'
			{
				$current = grammarAccess.getHintLevelAccess().getCONCEPTUALEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getHintLevelAccess().getCONCEPTUALEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='GUIDED'
			{
				$current = grammarAccess.getHintLevelAccess().getGUIDEDEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getHintLevelAccess().getGUIDEDEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='DIRECT'
			{
				$current = grammarAccess.getHintLevelAccess().getDIRECTEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getHintLevelAccess().getDIRECTEnumLiteralDeclaration_2());
			}
		)
	)
;

// Rule FeedbackStyle
ruleFeedbackStyle returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='CONCISE'
			{
				$current = grammarAccess.getFeedbackStyleAccess().getCONCISEEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getFeedbackStyleAccess().getCONCISEEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='EXPLANATORY'
			{
				$current = grammarAccess.getFeedbackStyleAccess().getEXPLANATORYEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getFeedbackStyleAccess().getEXPLANATORYEnumLiteralDeclaration_1());
			}
		)
	)
;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
