<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>com.project.mde</groupId><artifactId>mdedu-mde</artifactId><version>0.1.0-SNAPSHOT</version></parent><artifactId>com.project.mde.ui.transformations</artifactId><packaging>eclipse-test-plugin</packaging><build><plugins><plugin><groupId>org.eclipse.tycho</groupId><artifactId>tycho-surefire-plugin</artifactId><version>${tycho.version}</version><configuration><useUIHarness>false</useUIHarness><useUIThread>false</useUIThread><argLine>-Xmx384m</argLine></configuration></plugin></plugins></build></project>
