-- Normalized learning state. All timestamps are server-side UTC instants.
CREATE TABLE students (id uuid PRIMARY KEY, display_name varchar(80), created_at timestamptz NOT NULL, last_updated timestamptz NOT NULL, attempt_sequence bigint NOT NULL DEFAULT 0, version bigint NOT NULL DEFAULT 0);
CREATE TABLE concepts (id varchar(64) PRIMARY KEY, name varchar(120) NOT NULL, minimum_mastery_to_unlock double precision NOT NULL CHECK (minimum_mastery_to_unlock BETWEEN 0 AND 1), sort_order integer NOT NULL UNIQUE);
CREATE TABLE concept_prerequisites (concept_id varchar(64) NOT NULL REFERENCES concepts, prerequisite_id varchar(64) NOT NULL REFERENCES concepts, PRIMARY KEY(concept_id, prerequisite_id), CHECK(concept_id <> prerequisite_id));
CREATE TABLE learning_activities (id varchar(64) PRIMARY KEY, title varchar(160) NOT NULL, concept_id varchar(64) NOT NULL REFERENCES concepts, reinforcement boolean NOT NULL DEFAULT false);
CREATE TABLE error_patterns (id varchar(100) PRIMARY KEY, concept_id varchar(64) NOT NULL REFERENCES concepts, severity varchar(16) NOT NULL, pedagogical_meaning text NOT NULL);
CREATE TABLE student_concept_mastery (id uuid PRIMARY KEY, student_id uuid NOT NULL REFERENCES students, concept_id varchar(64) NOT NULL REFERENCES concepts, mastery_score double precision NOT NULL CHECK(mastery_score BETWEEN 0 AND 1), attempt_count integer NOT NULL CHECK(attempt_count >= 0), success_count integer NOT NULL CHECK(success_count >= 0), failure_count integer NOT NULL CHECK(failure_count >= 0), consecutive_failures integer NOT NULL CHECK(consecutive_failures >= 0), average_resolution_time double precision NOT NULL CHECK(average_resolution_time >= 0), hint_count integer NOT NULL CHECK(hint_count >= 0), last_updated timestamptz NOT NULL, UNIQUE(student_id,concept_id), CHECK(success_count + failure_count = attempt_count));
CREATE TABLE attempts (id uuid PRIMARY KEY, student_id uuid NOT NULL REFERENCES students, activity_id varchar(64) NOT NULL REFERENCES learning_activities, concept_id varchar(64) NOT NULL REFERENCES concepts, student_ordinal bigint NOT NULL, successful boolean NOT NULL, functional_passed boolean NOT NULL, resolution_time bigint NOT NULL CHECK(resolution_time BETWEEN 0 AND 86400000), hint_count integer NOT NULL CHECK(hint_count BETWEEN 0 AND 100), submitted_at timestamptz NOT NULL, policy_version integer NOT NULL, mastery_before double precision NOT NULL, mastery_delta double precision NOT NULL, mastery_after double precision NOT NULL, update_reasons varchar(200) NOT NULL, UNIQUE(student_id,student_ordinal));
CREATE INDEX attempts_recent ON attempts(student_id,concept_id,student_ordinal DESC);
CREATE TABLE attempt_error_patterns (attempt_id uuid NOT NULL REFERENCES attempts, pattern_id varchar(100) NOT NULL REFERENCES error_patterns, pattern_order integer NOT NULL, PRIMARY KEY(attempt_id,pattern_order), UNIQUE(attempt_id,pattern_id));
CREATE TABLE student_activity_progress (id uuid PRIMARY KEY, student_id uuid NOT NULL REFERENCES students, activity_id varchar(64) NOT NULL REFERENCES learning_activities, completed_at timestamptz, unlocked_at timestamptz, UNIQUE(student_id,activity_id));
CREATE TABLE hint_usages (id uuid PRIMARY KEY, student_id uuid NOT NULL REFERENCES students, activity_id varchar(64) NOT NULL REFERENCES learning_activities, hint_level integer NOT NULL CHECK(hint_level BETWEEN 1 AND 3), used_at timestamptz NOT NULL);
INSERT INTO concepts VALUES ('SEQUENCES','Secuencias',0.05,1);
INSERT INTO concepts VALUES ('VARIABLES','Variables',0.05,2);
INSERT INTO concepts VALUES ('CONDITIONALS','Condicionales',0.05,3);
INSERT INTO concepts VALUES ('LOOPS','Ciclos',0.05,4);
INSERT INTO learning_activities VALUES ('SEQUENCES','Primeros pasos','SEQUENCES',false);
INSERT INTO concept_prerequisites VALUES ('VARIABLES','SEQUENCES');
INSERT INTO learning_activities VALUES ('VARIABLES','Guarda y cambia','VARIABLES',false);
INSERT INTO concept_prerequisites VALUES ('CONDITIONALS','VARIABLES');
INSERT INTO learning_activities VALUES ('CONDITIONALS','La puerta y la llave','CONDITIONALS',false);
INSERT INTO concept_prerequisites VALUES ('LOOPS','CONDITIONALS');
INSERT INTO learning_activities VALUES ('LOOPS','Repite el camino','LOOPS',false);
INSERT INTO error_patterns VALUES ('WRONG_ORDER','SEQUENCES','ERROR','Las acciones estÃ¡n presentes, pero su orden cambia el recorrido.');
INSERT INTO error_patterns VALUES ('UNNECESSARY_INSTRUCTION','SEQUENCES','WARNING','Tu secuencia incluye acciones adicionales al recorrido de referencia.');
INSERT INTO error_patterns VALUES ('MISSING_ACTION','SEQUENCES','ERROR','Tu secuencia conserva el orden, pero aÃºn faltan acciones del recorrido.');
INSERT INTO error_patterns VALUES ('UNUSED_VARIABLE','VARIABLES','WARNING','Declaraste una variable sin leerla ni asignarle otro valor despuÃ©s.');
INSERT INTO error_patterns VALUES ('REDUNDANT_REASSIGNMENT','VARIABLES','WARNING','Una asignaciÃ³n queda sobrescrita antes de que se lea su valor.');
INSERT INTO error_patterns VALUES ('INCORRECT_UPDATE','VARIABLES','ERROR','El cambio observado todavÃ­a no cumple el objetivo de pasar de 0 a 1.');
INSERT INTO error_patterns VALUES ('MISSING_CONDITION','CONDITIONALS','ERROR','Falta el condicional que representa la decisiÃ³n de esta actividad.');
INSERT INTO error_patterns VALUES ('IDENTICAL_BRANCHES','CONDITIONALS','ERROR','Las dos alternativas contienen las mismas instrucciones.');
INSERT INTO error_patterns VALUES ('CONSTANT_CONDITION','CONDITIONALS','ERROR','La condiciÃ³n se puede resolver sin observar el mundo ni una variable.');
INSERT INTO error_patterns VALUES ('MISSING_REQUIRED_BRANCH','CONDITIONALS','ERROR','Falta una alternativa o una de las ramas estÃ¡ vacÃ­a.');
INSERT INTO error_patterns VALUES ('REPETITIVE_SEQUENCE_WITHOUT_LOOP','LOOPS','ERROR','Tu programa repite manualmente varias veces las mismas instrucciones.');
INSERT INTO error_patterns VALUES ('LOOP_NEVER_EXECUTES','LOOPS','ERROR','Este ciclo no llega a ejecutar su cuerpo al comenzar.');
INSERT INTO error_patterns VALUES ('INCORRECT_REPETITION_COUNT','LOOPS','ERROR','El ciclo seleccionado no coincide con las iteraciones esperadas para el camino.');
INSERT INTO error_patterns VALUES ('UNNECESSARY_LOOP','LOOPS','WARNING','Este Repetir ejecuta su cuerpo una sola vez.');
INSERT INTO error_patterns VALUES ('POSSIBLE_INFINITE_LOOP','LOOPS','ERROR','La condiciÃ³n permanece constante en verdadero o el control Mientras agotÃ³ el presupuesto.');
