/*
 * generated by Xtext
 */
package com.project.mde.adaptation.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAdaptationRulesScopeProvider extends DelegatingScopeProvider {
}
