/*
 * generated by Xtext
 */
package com.project.mde.adaptation.dsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class AdaptationRulesGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class AdaptationRuleSetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.AdaptationRuleSet");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRulesetKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cVersionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cVersionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cVersionSignedIntParserRuleCall_3_0 = (RuleCall)cVersionAssignment_3.eContents().get(0);
		private final Assignment cRulesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cRulesAdaptationRuleParserRuleCall_4_0 = (RuleCall)cRulesAssignment_4.eContents().get(0);
		
		//AdaptationRuleSet returns adaptation::AdaptationRuleSet:
		// 'ruleset' name=STRING 'version' version=SignedInt rules+=AdaptationRule*;
		@Override public ParserRule getRule() { return rule; }
		
		//'ruleset' name=STRING 'version' version=SignedInt rules+=AdaptationRule*
		public Group getGroup() { return cGroup; }
		
		//'ruleset'
		public Keyword getRulesetKeyword_0() { return cRulesetKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//'version'
		public Keyword getVersionKeyword_2() { return cVersionKeyword_2; }
		
		//version=SignedInt
		public Assignment getVersionAssignment_3() { return cVersionAssignment_3; }
		
		//SignedInt
		public RuleCall getVersionSignedIntParserRuleCall_3_0() { return cVersionSignedIntParserRuleCall_3_0; }
		
		//rules+=AdaptationRule*
		public Assignment getRulesAssignment_4() { return cRulesAssignment_4; }
		
		//AdaptationRule
		public RuleCall getRulesAdaptationRuleParserRuleCall_4_0() { return cRulesAdaptationRuleParserRuleCall_4_0; }
	}
	public class AdaptationRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.AdaptationRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRuleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdIDTerminalRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cNameKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cNameAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cNameAssignment_2_1.eContents().get(0);
		private final Keyword cVersionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cVersionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cVersionSignedIntParserRuleCall_4_0 = (RuleCall)cVersionAssignment_4.eContents().get(0);
		private final Keyword cEnabledKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cEnabledAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cEnabledBooleanParserRuleCall_6_0 = (RuleCall)cEnabledAssignment_6.eContents().get(0);
		private final Keyword cOnKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cEventAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cEventEventParserRuleCall_8_0 = (RuleCall)cEventAssignment_8.eContents().get(0);
		private final Keyword cWhenKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cConditionAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cConditionConditionParserRuleCall_10_0 = (RuleCall)cConditionAssignment_10.eContents().get(0);
		private final Keyword cThenKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cActionsAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cActionsActionParserRuleCall_12_0 = (RuleCall)cActionsAssignment_12.eContents().get(0);
		private final Keyword cPriorityKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cPriorityAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cPrioritySignedIntParserRuleCall_14_0 = (RuleCall)cPriorityAssignment_14.eContents().get(0);
		
		//AdaptationRule returns adaptation::AdaptationRule:
		// 'rule' id=ID ('name' name=STRING)? 'version' version=SignedInt
		// 'enabled' enabled=Boolean 'on' event=Event 'when' condition=Condition?
		// 'then' actions+=Action* 'priority' priority=SignedInt;
		@Override public ParserRule getRule() { return rule; }
		
		//'rule' id=ID ('name' name=STRING)? 'version' version=SignedInt
		//'enabled' enabled=Boolean 'on' event=Event 'when' condition=Condition?
		//'then' actions+=Action* 'priority' priority=SignedInt
		public Group getGroup() { return cGroup; }
		
		//'rule'
		public Keyword getRuleKeyword_0() { return cRuleKeyword_0; }
		
		//id=ID
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//ID
		public RuleCall getIdIDTerminalRuleCall_1_0() { return cIdIDTerminalRuleCall_1_0; }
		
		//('name' name=STRING)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'name'
		public Keyword getNameKeyword_2_0() { return cNameKeyword_2_0; }
		
		//name=STRING
		public Assignment getNameAssignment_2_1() { return cNameAssignment_2_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_1_0() { return cNameSTRINGTerminalRuleCall_2_1_0; }
		
		//'version'
		public Keyword getVersionKeyword_3() { return cVersionKeyword_3; }
		
		//version=SignedInt
		public Assignment getVersionAssignment_4() { return cVersionAssignment_4; }
		
		//SignedInt
		public RuleCall getVersionSignedIntParserRuleCall_4_0() { return cVersionSignedIntParserRuleCall_4_0; }
		
		//'enabled'
		public Keyword getEnabledKeyword_5() { return cEnabledKeyword_5; }
		
		//enabled=Boolean
		public Assignment getEnabledAssignment_6() { return cEnabledAssignment_6; }
		
		//Boolean
		public RuleCall getEnabledBooleanParserRuleCall_6_0() { return cEnabledBooleanParserRuleCall_6_0; }
		
		//'on'
		public Keyword getOnKeyword_7() { return cOnKeyword_7; }
		
		//event=Event
		public Assignment getEventAssignment_8() { return cEventAssignment_8; }
		
		//Event
		public RuleCall getEventEventParserRuleCall_8_0() { return cEventEventParserRuleCall_8_0; }
		
		//'when'
		public Keyword getWhenKeyword_9() { return cWhenKeyword_9; }
		
		//condition=Condition?
		public Assignment getConditionAssignment_10() { return cConditionAssignment_10; }
		
		//Condition
		public RuleCall getConditionConditionParserRuleCall_10_0() { return cConditionConditionParserRuleCall_10_0; }
		
		//'then'
		public Keyword getThenKeyword_11() { return cThenKeyword_11; }
		
		//actions+=Action*
		public Assignment getActionsAssignment_12() { return cActionsAssignment_12; }
		
		//Action
		public RuleCall getActionsActionParserRuleCall_12_0() { return cActionsActionParserRuleCall_12_0; }
		
		//'priority'
		public Keyword getPriorityKeyword_13() { return cPriorityKeyword_13; }
		
		//priority=SignedInt
		public Assignment getPriorityAssignment_14() { return cPriorityAssignment_14; }
		
		//SignedInt
		public RuleCall getPrioritySignedIntParserRuleCall_14_0() { return cPrioritySignedIntParserRuleCall_14_0; }
	}
	public class EventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.Event");
		private final Assignment cTypeAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cTypeEventTypeEnumRuleCall_0 = (RuleCall)cTypeAssignment.eContents().get(0);
		
		//Event returns adaptation::Event: type=EventType;
		@Override public ParserRule getRule() { return rule; }
		
		//type=EventType
		public Assignment getTypeAssignment() { return cTypeAssignment; }
		
		//EventType
		public RuleCall getTypeEventTypeEnumRuleCall_0() { return cTypeEventTypeEnumRuleCall_0; }
	}
	public class ConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.Condition");
		private final RuleCall cOrConditionParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Condition returns adaptation::Condition: OrCondition;
		@Override public ParserRule getRule() { return rule; }
		
		//OrCondition
		public RuleCall getOrConditionParserRuleCall() { return cOrConditionParserRuleCall; }
	}
	public class OrConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.OrCondition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cAndConditionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cLogicalConditionLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperatorOrEnumRuleCall_1_1_0 = (RuleCall)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightAndConditionParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//OrCondition returns adaptation::Condition:
		// AndCondition ({adaptation::LogicalCondition.left=current} operator=Or right=AndCondition)*;
		@Override public ParserRule getRule() { return rule; }
		
		//AndCondition ({adaptation::LogicalCondition.left=current} operator=Or right=AndCondition)*
		public Group getGroup() { return cGroup; }
		
		//AndCondition
		public RuleCall getAndConditionParserRuleCall_0() { return cAndConditionParserRuleCall_0; }
		
		//({adaptation::LogicalCondition.left=current} operator=Or right=AndCondition)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{adaptation::LogicalCondition.left=current}
		public Action getLogicalConditionLeftAction_1_0() { return cLogicalConditionLeftAction_1_0; }
		
		//operator=Or
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }
		
		//Or
		public RuleCall getOperatorOrEnumRuleCall_1_1_0() { return cOperatorOrEnumRuleCall_1_1_0; }
		
		//right=AndCondition
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//AndCondition
		public RuleCall getRightAndConditionParserRuleCall_1_2_0() { return cRightAndConditionParserRuleCall_1_2_0; }
	}
	public class AndConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.AndCondition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cUnaryConditionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cLogicalConditionLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperatorAndEnumRuleCall_1_1_0 = (RuleCall)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightUnaryConditionParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//AndCondition returns adaptation::Condition:
		// UnaryCondition ({adaptation::LogicalCondition.left=current} operator=And right=UnaryCondition)*;
		@Override public ParserRule getRule() { return rule; }
		
		//UnaryCondition ({adaptation::LogicalCondition.left=current} operator=And right=UnaryCondition)*
		public Group getGroup() { return cGroup; }
		
		//UnaryCondition
		public RuleCall getUnaryConditionParserRuleCall_0() { return cUnaryConditionParserRuleCall_0; }
		
		//({adaptation::LogicalCondition.left=current} operator=And right=UnaryCondition)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{adaptation::LogicalCondition.left=current}
		public Action getLogicalConditionLeftAction_1_0() { return cLogicalConditionLeftAction_1_0; }
		
		//operator=And
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }
		
		//And
		public RuleCall getOperatorAndEnumRuleCall_1_1_0() { return cOperatorAndEnumRuleCall_1_1_0; }
		
		//right=UnaryCondition
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//UnaryCondition
		public RuleCall getRightUnaryConditionParserRuleCall_1_2_0() { return cRightUnaryConditionParserRuleCall_1_2_0; }
	}
	public class UnaryConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.UnaryCondition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cNotConditionAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cNotKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cOperandAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cOperandUnaryConditionParserRuleCall_0_2_0 = (RuleCall)cOperandAssignment_0_2.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cConditionParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final RuleCall cComparisonConditionParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//UnaryCondition returns adaptation::Condition:
		// {adaptation::NotCondition} 'not' operand=UnaryCondition | '(' Condition ')' | ComparisonCondition;
		@Override public ParserRule getRule() { return rule; }
		
		//{adaptation::NotCondition} 'not' operand=UnaryCondition | '(' Condition ')' | ComparisonCondition
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{adaptation::NotCondition} 'not' operand=UnaryCondition
		public Group getGroup_0() { return cGroup_0; }
		
		//{adaptation::NotCondition}
		public Action getNotConditionAction_0_0() { return cNotConditionAction_0_0; }
		
		//'not'
		public Keyword getNotKeyword_0_1() { return cNotKeyword_0_1; }
		
		//operand=UnaryCondition
		public Assignment getOperandAssignment_0_2() { return cOperandAssignment_0_2; }
		
		//UnaryCondition
		public RuleCall getOperandUnaryConditionParserRuleCall_0_2_0() { return cOperandUnaryConditionParserRuleCall_0_2_0; }
		
		//'(' Condition ')'
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//Condition
		public RuleCall getConditionParserRuleCall_1_1() { return cConditionParserRuleCall_1_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
		
		//ComparisonCondition
		public RuleCall getComparisonConditionParserRuleCall_2() { return cComparisonConditionParserRuleCall_2; }
	}
	public class ComparisonConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.ComparisonCondition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cAttributeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cAttributeIDTerminalRuleCall_0_0 = (RuleCall)cAttributeAssignment_0.eContents().get(0);
		private final Assignment cOperatorAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cOperatorComparisonOperatorEnumRuleCall_1_0 = (RuleCall)cOperatorAssignment_1.eContents().get(0);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueValueParserRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//ComparisonCondition returns adaptation::ComparisonCondition:
		// attribute=ID operator=ComparisonOperator value=Value;
		@Override public ParserRule getRule() { return rule; }
		
		//attribute=ID operator=ComparisonOperator value=Value
		public Group getGroup() { return cGroup; }
		
		//attribute=ID
		public Assignment getAttributeAssignment_0() { return cAttributeAssignment_0; }
		
		//ID
		public RuleCall getAttributeIDTerminalRuleCall_0_0() { return cAttributeIDTerminalRuleCall_0_0; }
		
		//operator=ComparisonOperator
		public Assignment getOperatorAssignment_1() { return cOperatorAssignment_1; }
		
		//ComparisonOperator
		public RuleCall getOperatorComparisonOperatorEnumRuleCall_1_0() { return cOperatorComparisonOperatorEnumRuleCall_1_0; }
		
		//value=Value
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }
		
		//Value
		public RuleCall getValueValueParserRuleCall_2_0() { return cValueValueParserRuleCall_2_0; }
	}
	public class ValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.Value");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStringValueParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDecimalValueParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cIntegerValueParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cBooleanValueParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Value returns adaptation::Value: StringValue | DecimalValue | IntegerValue | BooleanValue;
		@Override public ParserRule getRule() { return rule; }
		
		//StringValue | DecimalValue | IntegerValue | BooleanValue
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//StringValue
		public RuleCall getStringValueParserRuleCall_0() { return cStringValueParserRuleCall_0; }
		
		//DecimalValue
		public RuleCall getDecimalValueParserRuleCall_1() { return cDecimalValueParserRuleCall_1; }
		
		//IntegerValue
		public RuleCall getIntegerValueParserRuleCall_2() { return cIntegerValueParserRuleCall_2; }
		
		//BooleanValue
		public RuleCall getBooleanValueParserRuleCall_3() { return cBooleanValueParserRuleCall_3; }
	}
	public class StringValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.StringValue");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//StringValue returns adaptation::StringValue: value=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//value=STRING
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_0() { return cValueSTRINGTerminalRuleCall_0; }
	}
	public class DecimalValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.DecimalValue");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueDecimalParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//DecimalValue returns adaptation::DecimalValue: value=Decimal;
		@Override public ParserRule getRule() { return rule; }
		
		//value=Decimal
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//Decimal
		public RuleCall getValueDecimalParserRuleCall_0() { return cValueDecimalParserRuleCall_0; }
	}
	public class IntegerValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.IntegerValue");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueLongParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//IntegerValue returns adaptation::IntegerValue: value=Long;
		@Override public ParserRule getRule() { return rule; }
		
		//value=Long
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//Long
		public RuleCall getValueLongParserRuleCall_0() { return cValueLongParserRuleCall_0; }
	}
	public class BooleanValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.BooleanValue");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueBooleanParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//BooleanValue returns adaptation::BooleanValue: value=Boolean;
		@Override public ParserRule getRule() { return rule; }
		
		//value=Boolean
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//Boolean
		public RuleCall getValueBooleanParserRuleCall_0() { return cValueBooleanParserRuleCall_0; }
	}
	public class SignedIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.SignedInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//SignedInt returns ecore::EInt: '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class LongElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.Long");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//Long returns ecore::ELong: '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class DecimalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.Decimal");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		
		//Decimal returns ecore::EBigDecimal: '-'? INT '.' INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT '.' INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
	}
	public class BooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.Boolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//Boolean returns ecore::EBoolean: 'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.Action");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cActionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeActionTypeEnumRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cParametersAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cParametersAdaptationParametersParserRuleCall_2_0 = (RuleCall)cParametersAssignment_2.eContents().get(0);
		
		//Action returns adaptation::Action: 'action' type=ActionType parameters=AdaptationParameters?;
		@Override public ParserRule getRule() { return rule; }
		
		//'action' type=ActionType parameters=AdaptationParameters?
		public Group getGroup() { return cGroup; }
		
		//'action'
		public Keyword getActionKeyword_0() { return cActionKeyword_0; }
		
		//type=ActionType
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//ActionType
		public RuleCall getTypeActionTypeEnumRuleCall_1_0() { return cTypeActionTypeEnumRuleCall_1_0; }
		
		//parameters=AdaptationParameters?
		public Assignment getParametersAssignment_2() { return cParametersAssignment_2; }
		
		//AdaptationParameters
		public RuleCall getParametersAdaptationParametersParserRuleCall_2_0() { return cParametersAdaptationParametersParserRuleCall_2_0; }
	}
	public class AdaptationParametersElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.AdaptationParameters");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cLevelKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cHintLevelAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cHintLevelHintLevelEnumRuleCall_0_1_0 = (RuleCall)cHintLevelAssignment_0_1.eContents().get(0);
		private final Group cGroup_0_2 = (Group)cGroup_0.eContents().get(2);
		private final Keyword cStyleKeyword_0_2_0 = (Keyword)cGroup_0_2.eContents().get(0);
		private final Assignment cFeedbackStyleAssignment_0_2_1 = (Assignment)cGroup_0_2.eContents().get(1);
		private final RuleCall cFeedbackStyleFeedbackStyleEnumRuleCall_0_2_1_0 = (RuleCall)cFeedbackStyleAssignment_0_2_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cStyleKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cFeedbackStyleAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cFeedbackStyleFeedbackStyleEnumRuleCall_1_1_0 = (RuleCall)cFeedbackStyleAssignment_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cLevelKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cHintLevelAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cHintLevelHintLevelEnumRuleCall_1_2_1_0 = (RuleCall)cHintLevelAssignment_1_2_1.eContents().get(0);
		
		//AdaptationParameters returns adaptation::AdaptationParameters:
		// 'level' hintLevel=HintLevel ('style' feedbackStyle=FeedbackStyle)? |
		// 'style' feedbackStyle=FeedbackStyle ('level' hintLevel=HintLevel)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'level' hintLevel=HintLevel ('style' feedbackStyle=FeedbackStyle)? |
		//'style' feedbackStyle=FeedbackStyle ('level' hintLevel=HintLevel)?
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'level' hintLevel=HintLevel ('style' feedbackStyle=FeedbackStyle)?
		public Group getGroup_0() { return cGroup_0; }
		
		//'level'
		public Keyword getLevelKeyword_0_0() { return cLevelKeyword_0_0; }
		
		//hintLevel=HintLevel
		public Assignment getHintLevelAssignment_0_1() { return cHintLevelAssignment_0_1; }
		
		//HintLevel
		public RuleCall getHintLevelHintLevelEnumRuleCall_0_1_0() { return cHintLevelHintLevelEnumRuleCall_0_1_0; }
		
		//('style' feedbackStyle=FeedbackStyle)?
		public Group getGroup_0_2() { return cGroup_0_2; }
		
		//'style'
		public Keyword getStyleKeyword_0_2_0() { return cStyleKeyword_0_2_0; }
		
		//feedbackStyle=FeedbackStyle
		public Assignment getFeedbackStyleAssignment_0_2_1() { return cFeedbackStyleAssignment_0_2_1; }
		
		//FeedbackStyle
		public RuleCall getFeedbackStyleFeedbackStyleEnumRuleCall_0_2_1_0() { return cFeedbackStyleFeedbackStyleEnumRuleCall_0_2_1_0; }
		
		//'style' feedbackStyle=FeedbackStyle ('level' hintLevel=HintLevel)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'style'
		public Keyword getStyleKeyword_1_0() { return cStyleKeyword_1_0; }
		
		//feedbackStyle=FeedbackStyle
		public Assignment getFeedbackStyleAssignment_1_1() { return cFeedbackStyleAssignment_1_1; }
		
		//FeedbackStyle
		public RuleCall getFeedbackStyleFeedbackStyleEnumRuleCall_1_1_0() { return cFeedbackStyleFeedbackStyleEnumRuleCall_1_1_0; }
		
		//('level' hintLevel=HintLevel)?
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//'level'
		public Keyword getLevelKeyword_1_2_0() { return cLevelKeyword_1_2_0; }
		
		//hintLevel=HintLevel
		public Assignment getHintLevelAssignment_1_2_1() { return cHintLevelAssignment_1_2_1; }
		
		//HintLevel
		public RuleCall getHintLevelHintLevelEnumRuleCall_1_2_1_0() { return cHintLevelHintLevelEnumRuleCall_1_2_1_0; }
	}
	
	public class EventTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.EventType");
		private final EnumLiteralDeclaration cATTEMPT_EVALUATEDEnumLiteralDeclaration = (EnumLiteralDeclaration)rule.eContents().get(1);
		private final Keyword cATTEMPT_EVALUATEDATTEMPT_EVALUATEDKeyword_0 = (Keyword)cATTEMPT_EVALUATEDEnumLiteralDeclaration.eContents().get(0);
		
		//enum EventType returns adaptation::EventType: ATTEMPT_EVALUATED;
		public EnumRule getRule() { return rule; }
		
		//ATTEMPT_EVALUATED
		public EnumLiteralDeclaration getATTEMPT_EVALUATEDEnumLiteralDeclaration() { return cATTEMPT_EVALUATEDEnumLiteralDeclaration; }
		
		public Keyword getATTEMPT_EVALUATEDATTEMPT_EVALUATEDKeyword_0() { return cATTEMPT_EVALUATEDATTEMPT_EVALUATEDKeyword_0; }
	}
	public class OrElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.Or");
		private final EnumLiteralDeclaration cOREnumLiteralDeclaration = (EnumLiteralDeclaration)rule.eContents().get(1);
		private final Keyword cOROrKeyword_0 = (Keyword)cOREnumLiteralDeclaration.eContents().get(0);
		
		//enum Or returns adaptation::LogicalOperator: OR='or';
		public EnumRule getRule() { return rule; }
		
		//OR='or'
		public EnumLiteralDeclaration getOREnumLiteralDeclaration() { return cOREnumLiteralDeclaration; }
		
		//'or'
		public Keyword getOROrKeyword_0() { return cOROrKeyword_0; }
	}
	public class AndElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.And");
		private final EnumLiteralDeclaration cANDEnumLiteralDeclaration = (EnumLiteralDeclaration)rule.eContents().get(1);
		private final Keyword cANDAndKeyword_0 = (Keyword)cANDEnumLiteralDeclaration.eContents().get(0);
		
		//enum And returns adaptation::LogicalOperator: AND='and';
		public EnumRule getRule() { return rule; }
		
		//AND='and'
		public EnumLiteralDeclaration getANDEnumLiteralDeclaration() { return cANDEnumLiteralDeclaration; }
		
		//'and'
		public Keyword getANDAndKeyword_0() { return cANDAndKeyword_0; }
	}
	public class ComparisonOperatorElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.ComparisonOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cEQEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cEQEqualsSignEqualsSignKeyword_0_0 = (Keyword)cEQEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cNEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cNEExclamationMarkEqualsSignKeyword_1_0 = (Keyword)cNEEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cGTEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cGTGreaterThanSignKeyword_2_0 = (Keyword)cGTEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cGEEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cGEGreaterThanSignEqualsSignKeyword_3_0 = (Keyword)cGEEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cLTEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cLTLessThanSignKeyword_4_0 = (Keyword)cLTEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cLEEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cLELessThanSignEqualsSignKeyword_5_0 = (Keyword)cLEEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cCONTAINSEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cCONTAINSContainsKeyword_6_0 = (Keyword)cCONTAINSEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum ComparisonOperator returns adaptation::ComparisonOperator:
		// EQ='==' | NE='!=' | GT='>' | GE='>=' | LT='<' | LE='<=' | CONTAINS='contains';
		public EnumRule getRule() { return rule; }
		
		//EQ='==' | NE='!=' | GT='>' | GE='>=' | LT='<' | LE='<=' | CONTAINS='contains'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//EQ='=='
		public EnumLiteralDeclaration getEQEnumLiteralDeclaration_0() { return cEQEnumLiteralDeclaration_0; }
		
		//'=='
		public Keyword getEQEqualsSignEqualsSignKeyword_0_0() { return cEQEqualsSignEqualsSignKeyword_0_0; }
		
		//NE='!='
		public EnumLiteralDeclaration getNEEnumLiteralDeclaration_1() { return cNEEnumLiteralDeclaration_1; }
		
		//'!='
		public Keyword getNEExclamationMarkEqualsSignKeyword_1_0() { return cNEExclamationMarkEqualsSignKeyword_1_0; }
		
		//GT='>'
		public EnumLiteralDeclaration getGTEnumLiteralDeclaration_2() { return cGTEnumLiteralDeclaration_2; }
		
		//'>'
		public Keyword getGTGreaterThanSignKeyword_2_0() { return cGTGreaterThanSignKeyword_2_0; }
		
		//GE='>='
		public EnumLiteralDeclaration getGEEnumLiteralDeclaration_3() { return cGEEnumLiteralDeclaration_3; }
		
		//'>='
		public Keyword getGEGreaterThanSignEqualsSignKeyword_3_0() { return cGEGreaterThanSignEqualsSignKeyword_3_0; }
		
		//LT='<'
		public EnumLiteralDeclaration getLTEnumLiteralDeclaration_4() { return cLTEnumLiteralDeclaration_4; }
		
		//'<'
		public Keyword getLTLessThanSignKeyword_4_0() { return cLTLessThanSignKeyword_4_0; }
		
		//LE='<='
		public EnumLiteralDeclaration getLEEnumLiteralDeclaration_5() { return cLEEnumLiteralDeclaration_5; }
		
		//'<='
		public Keyword getLELessThanSignEqualsSignKeyword_5_0() { return cLELessThanSignEqualsSignKeyword_5_0; }
		
		//CONTAINS='contains'
		public EnumLiteralDeclaration getCONTAINSEnumLiteralDeclaration_6() { return cCONTAINSEnumLiteralDeclaration_6; }
		
		//'contains'
		public Keyword getCONTAINSContainsKeyword_6_0() { return cCONTAINSContainsKeyword_6_0; }
	}
	public class ActionTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.ActionType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSHOW_HINTEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSHOW_HINTSHOW_HINTKeyword_0_0 = (Keyword)cSHOW_HINTEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCHANGE_HINT_LEVELEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCHANGE_HINT_LEVELCHANGE_HINT_LEVELKeyword_1_0 = (Keyword)cCHANGE_HINT_LEVELEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cREPEAT_ACTIVITYEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cREPEAT_ACTIVITYREPEAT_ACTIVITYKeyword_2_0 = (Keyword)cREPEAT_ACTIVITYEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cSELECT_REINFORCEMENT_ACTIVITYEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cSELECT_REINFORCEMENT_ACTIVITYSELECT_REINFORCEMENT_ACTIVITYKeyword_3_0 = (Keyword)cSELECT_REINFORCEMENT_ACTIVITYEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cADVANCE_TO_NEXT_CONCEPTEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cADVANCE_TO_NEXT_CONCEPTADVANCE_TO_NEXT_CONCEPTKeyword_4_0 = (Keyword)cADVANCE_TO_NEXT_CONCEPTEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cINCREASE_DIFFICULTYEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cINCREASE_DIFFICULTYINCREASE_DIFFICULTYKeyword_5_0 = (Keyword)cINCREASE_DIFFICULTYEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cDECREASE_DIFFICULTYEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cDECREASE_DIFFICULTYDECREASE_DIFFICULTYKeyword_6_0 = (Keyword)cDECREASE_DIFFICULTYEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cSHOW_CODE_VIEWEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cSHOW_CODE_VIEWSHOW_CODE_VIEWKeyword_7_0 = (Keyword)cSHOW_CODE_VIEWEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cHIDE_CODE_VIEWEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cHIDE_CODE_VIEWHIDE_CODE_VIEWKeyword_8_0 = (Keyword)cHIDE_CODE_VIEWEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cCHANGE_FEEDBACK_STYLEEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cCHANGE_FEEDBACK_STYLECHANGE_FEEDBACK_STYLEKeyword_9_0 = (Keyword)cCHANGE_FEEDBACK_STYLEEnumLiteralDeclaration_9.eContents().get(0);
		
		//enum ActionType returns adaptation::ActionType:
		// SHOW_HINT | CHANGE_HINT_LEVEL | REPEAT_ACTIVITY | SELECT_REINFORCEMENT_ACTIVITY |
		// ADVANCE_TO_NEXT_CONCEPT | INCREASE_DIFFICULTY | DECREASE_DIFFICULTY |
		// SHOW_CODE_VIEW | HIDE_CODE_VIEW | CHANGE_FEEDBACK_STYLE;
		public EnumRule getRule() { return rule; }
		
		//SHOW_HINT | CHANGE_HINT_LEVEL | REPEAT_ACTIVITY | SELECT_REINFORCEMENT_ACTIVITY |
		//ADVANCE_TO_NEXT_CONCEPT | INCREASE_DIFFICULTY | DECREASE_DIFFICULTY |
		//SHOW_CODE_VIEW | HIDE_CODE_VIEW | CHANGE_FEEDBACK_STYLE
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SHOW_HINT
		public EnumLiteralDeclaration getSHOW_HINTEnumLiteralDeclaration_0() { return cSHOW_HINTEnumLiteralDeclaration_0; }
		
		public Keyword getSHOW_HINTSHOW_HINTKeyword_0_0() { return cSHOW_HINTSHOW_HINTKeyword_0_0; }
		
		//CHANGE_HINT_LEVEL
		public EnumLiteralDeclaration getCHANGE_HINT_LEVELEnumLiteralDeclaration_1() { return cCHANGE_HINT_LEVELEnumLiteralDeclaration_1; }
		
		public Keyword getCHANGE_HINT_LEVELCHANGE_HINT_LEVELKeyword_1_0() { return cCHANGE_HINT_LEVELCHANGE_HINT_LEVELKeyword_1_0; }
		
		//REPEAT_ACTIVITY
		public EnumLiteralDeclaration getREPEAT_ACTIVITYEnumLiteralDeclaration_2() { return cREPEAT_ACTIVITYEnumLiteralDeclaration_2; }
		
		public Keyword getREPEAT_ACTIVITYREPEAT_ACTIVITYKeyword_2_0() { return cREPEAT_ACTIVITYREPEAT_ACTIVITYKeyword_2_0; }
		
		//SELECT_REINFORCEMENT_ACTIVITY
		public EnumLiteralDeclaration getSELECT_REINFORCEMENT_ACTIVITYEnumLiteralDeclaration_3() { return cSELECT_REINFORCEMENT_ACTIVITYEnumLiteralDeclaration_3; }
		
		public Keyword getSELECT_REINFORCEMENT_ACTIVITYSELECT_REINFORCEMENT_ACTIVITYKeyword_3_0() { return cSELECT_REINFORCEMENT_ACTIVITYSELECT_REINFORCEMENT_ACTIVITYKeyword_3_0; }
		
		//ADVANCE_TO_NEXT_CONCEPT
		public EnumLiteralDeclaration getADVANCE_TO_NEXT_CONCEPTEnumLiteralDeclaration_4() { return cADVANCE_TO_NEXT_CONCEPTEnumLiteralDeclaration_4; }
		
		public Keyword getADVANCE_TO_NEXT_CONCEPTADVANCE_TO_NEXT_CONCEPTKeyword_4_0() { return cADVANCE_TO_NEXT_CONCEPTADVANCE_TO_NEXT_CONCEPTKeyword_4_0; }
		
		//INCREASE_DIFFICULTY
		public EnumLiteralDeclaration getINCREASE_DIFFICULTYEnumLiteralDeclaration_5() { return cINCREASE_DIFFICULTYEnumLiteralDeclaration_5; }
		
		public Keyword getINCREASE_DIFFICULTYINCREASE_DIFFICULTYKeyword_5_0() { return cINCREASE_DIFFICULTYINCREASE_DIFFICULTYKeyword_5_0; }
		
		//DECREASE_DIFFICULTY
		public EnumLiteralDeclaration getDECREASE_DIFFICULTYEnumLiteralDeclaration_6() { return cDECREASE_DIFFICULTYEnumLiteralDeclaration_6; }
		
		public Keyword getDECREASE_DIFFICULTYDECREASE_DIFFICULTYKeyword_6_0() { return cDECREASE_DIFFICULTYDECREASE_DIFFICULTYKeyword_6_0; }
		
		//SHOW_CODE_VIEW
		public EnumLiteralDeclaration getSHOW_CODE_VIEWEnumLiteralDeclaration_7() { return cSHOW_CODE_VIEWEnumLiteralDeclaration_7; }
		
		public Keyword getSHOW_CODE_VIEWSHOW_CODE_VIEWKeyword_7_0() { return cSHOW_CODE_VIEWSHOW_CODE_VIEWKeyword_7_0; }
		
		//HIDE_CODE_VIEW
		public EnumLiteralDeclaration getHIDE_CODE_VIEWEnumLiteralDeclaration_8() { return cHIDE_CODE_VIEWEnumLiteralDeclaration_8; }
		
		public Keyword getHIDE_CODE_VIEWHIDE_CODE_VIEWKeyword_8_0() { return cHIDE_CODE_VIEWHIDE_CODE_VIEWKeyword_8_0; }
		
		//CHANGE_FEEDBACK_STYLE
		public EnumLiteralDeclaration getCHANGE_FEEDBACK_STYLEEnumLiteralDeclaration_9() { return cCHANGE_FEEDBACK_STYLEEnumLiteralDeclaration_9; }
		
		public Keyword getCHANGE_FEEDBACK_STYLECHANGE_FEEDBACK_STYLEKeyword_9_0() { return cCHANGE_FEEDBACK_STYLECHANGE_FEEDBACK_STYLEKeyword_9_0; }
	}
	public class HintLevelElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.HintLevel");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCONCEPTUALEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCONCEPTUALCONCEPTUALKeyword_0_0 = (Keyword)cCONCEPTUALEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cGUIDEDEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cGUIDEDGUIDEDKeyword_1_0 = (Keyword)cGUIDEDEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cDIRECTEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cDIRECTDIRECTKeyword_2_0 = (Keyword)cDIRECTEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum HintLevel returns adaptation::HintLevel: CONCEPTUAL | GUIDED | DIRECT;
		public EnumRule getRule() { return rule; }
		
		//CONCEPTUAL | GUIDED | DIRECT
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CONCEPTUAL
		public EnumLiteralDeclaration getCONCEPTUALEnumLiteralDeclaration_0() { return cCONCEPTUALEnumLiteralDeclaration_0; }
		
		public Keyword getCONCEPTUALCONCEPTUALKeyword_0_0() { return cCONCEPTUALCONCEPTUALKeyword_0_0; }
		
		//GUIDED
		public EnumLiteralDeclaration getGUIDEDEnumLiteralDeclaration_1() { return cGUIDEDEnumLiteralDeclaration_1; }
		
		public Keyword getGUIDEDGUIDEDKeyword_1_0() { return cGUIDEDGUIDEDKeyword_1_0; }
		
		//DIRECT
		public EnumLiteralDeclaration getDIRECTEnumLiteralDeclaration_2() { return cDIRECTEnumLiteralDeclaration_2; }
		
		public Keyword getDIRECTDIRECTKeyword_2_0() { return cDIRECTDIRECTKeyword_2_0; }
	}
	public class FeedbackStyleElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "com.project.mde.adaptation.dsl.AdaptationRules.FeedbackStyle");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCONCISEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCONCISECONCISEKeyword_0_0 = (Keyword)cCONCISEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cEXPLANATORYEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cEXPLANATORYEXPLANATORYKeyword_1_0 = (Keyword)cEXPLANATORYEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum FeedbackStyle returns adaptation::FeedbackStyle: CONCISE | EXPLANATORY;
		public EnumRule getRule() { return rule; }
		
		//CONCISE | EXPLANATORY
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CONCISE
		public EnumLiteralDeclaration getCONCISEEnumLiteralDeclaration_0() { return cCONCISEEnumLiteralDeclaration_0; }
		
		public Keyword getCONCISECONCISEKeyword_0_0() { return cCONCISECONCISEKeyword_0_0; }
		
		//EXPLANATORY
		public EnumLiteralDeclaration getEXPLANATORYEnumLiteralDeclaration_1() { return cEXPLANATORYEnumLiteralDeclaration_1; }
		
		public Keyword getEXPLANATORYEXPLANATORYKeyword_1_0() { return cEXPLANATORYEXPLANATORYKeyword_1_0; }
	}
	
	private final AdaptationRuleSetElements pAdaptationRuleSet;
	private final AdaptationRuleElements pAdaptationRule;
	private final EventElements pEvent;
	private final EventTypeElements eEventType;
	private final ConditionElements pCondition;
	private final OrConditionElements pOrCondition;
	private final AndConditionElements pAndCondition;
	private final OrElements eOr;
	private final AndElements eAnd;
	private final UnaryConditionElements pUnaryCondition;
	private final ComparisonConditionElements pComparisonCondition;
	private final ComparisonOperatorElements eComparisonOperator;
	private final ValueElements pValue;
	private final StringValueElements pStringValue;
	private final DecimalValueElements pDecimalValue;
	private final IntegerValueElements pIntegerValue;
	private final BooleanValueElements pBooleanValue;
	private final SignedIntElements pSignedInt;
	private final LongElements pLong;
	private final DecimalElements pDecimal;
	private final BooleanElements pBoolean;
	private final ActionElements pAction;
	private final AdaptationParametersElements pAdaptationParameters;
	private final ActionTypeElements eActionType;
	private final HintLevelElements eHintLevel;
	private final FeedbackStyleElements eFeedbackStyle;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public AdaptationRulesGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pAdaptationRuleSet = new AdaptationRuleSetElements();
		this.pAdaptationRule = new AdaptationRuleElements();
		this.pEvent = new EventElements();
		this.eEventType = new EventTypeElements();
		this.pCondition = new ConditionElements();
		this.pOrCondition = new OrConditionElements();
		this.pAndCondition = new AndConditionElements();
		this.eOr = new OrElements();
		this.eAnd = new AndElements();
		this.pUnaryCondition = new UnaryConditionElements();
		this.pComparisonCondition = new ComparisonConditionElements();
		this.eComparisonOperator = new ComparisonOperatorElements();
		this.pValue = new ValueElements();
		this.pStringValue = new StringValueElements();
		this.pDecimalValue = new DecimalValueElements();
		this.pIntegerValue = new IntegerValueElements();
		this.pBooleanValue = new BooleanValueElements();
		this.pSignedInt = new SignedIntElements();
		this.pLong = new LongElements();
		this.pDecimal = new DecimalElements();
		this.pBoolean = new BooleanElements();
		this.pAction = new ActionElements();
		this.pAdaptationParameters = new AdaptationParametersElements();
		this.eActionType = new ActionTypeElements();
		this.eHintLevel = new HintLevelElements();
		this.eFeedbackStyle = new FeedbackStyleElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.project.mde.adaptation.dsl.AdaptationRules".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//AdaptationRuleSet returns adaptation::AdaptationRuleSet:
	// 'ruleset' name=STRING 'version' version=SignedInt rules+=AdaptationRule*;
	public AdaptationRuleSetElements getAdaptationRuleSetAccess() {
		return pAdaptationRuleSet;
	}
	
	public ParserRule getAdaptationRuleSetRule() {
		return getAdaptationRuleSetAccess().getRule();
	}
	
	//AdaptationRule returns adaptation::AdaptationRule:
	// 'rule' id=ID ('name' name=STRING)? 'version' version=SignedInt
	// 'enabled' enabled=Boolean 'on' event=Event 'when' condition=Condition?
	// 'then' actions+=Action* 'priority' priority=SignedInt;
	public AdaptationRuleElements getAdaptationRuleAccess() {
		return pAdaptationRule;
	}
	
	public ParserRule getAdaptationRuleRule() {
		return getAdaptationRuleAccess().getRule();
	}
	
	//Event returns adaptation::Event: type=EventType;
	public EventElements getEventAccess() {
		return pEvent;
	}
	
	public ParserRule getEventRule() {
		return getEventAccess().getRule();
	}
	
	//enum EventType returns adaptation::EventType: ATTEMPT_EVALUATED;
	public EventTypeElements getEventTypeAccess() {
		return eEventType;
	}
	
	public EnumRule getEventTypeRule() {
		return getEventTypeAccess().getRule();
	}
	
	//Condition returns adaptation::Condition: OrCondition;
	public ConditionElements getConditionAccess() {
		return pCondition;
	}
	
	public ParserRule getConditionRule() {
		return getConditionAccess().getRule();
	}
	
	//OrCondition returns adaptation::Condition:
	// AndCondition ({adaptation::LogicalCondition.left=current} operator=Or right=AndCondition)*;
	public OrConditionElements getOrConditionAccess() {
		return pOrCondition;
	}
	
	public ParserRule getOrConditionRule() {
		return getOrConditionAccess().getRule();
	}
	
	//AndCondition returns adaptation::Condition:
	// UnaryCondition ({adaptation::LogicalCondition.left=current} operator=And right=UnaryCondition)*;
	public AndConditionElements getAndConditionAccess() {
		return pAndCondition;
	}
	
	public ParserRule getAndConditionRule() {
		return getAndConditionAccess().getRule();
	}
	
	//enum Or returns adaptation::LogicalOperator: OR='or';
	public OrElements getOrAccess() {
		return eOr;
	}
	
	public EnumRule getOrRule() {
		return getOrAccess().getRule();
	}
	
	//enum And returns adaptation::LogicalOperator: AND='and';
	public AndElements getAndAccess() {
		return eAnd;
	}
	
	public EnumRule getAndRule() {
		return getAndAccess().getRule();
	}
	
	//UnaryCondition returns adaptation::Condition:
	// {adaptation::NotCondition} 'not' operand=UnaryCondition | '(' Condition ')' | ComparisonCondition;
	public UnaryConditionElements getUnaryConditionAccess() {
		return pUnaryCondition;
	}
	
	public ParserRule getUnaryConditionRule() {
		return getUnaryConditionAccess().getRule();
	}
	
	//ComparisonCondition returns adaptation::ComparisonCondition:
	// attribute=ID operator=ComparisonOperator value=Value;
	public ComparisonConditionElements getComparisonConditionAccess() {
		return pComparisonCondition;
	}
	
	public ParserRule getComparisonConditionRule() {
		return getComparisonConditionAccess().getRule();
	}
	
	//enum ComparisonOperator returns adaptation::ComparisonOperator:
	// EQ='==' | NE='!=' | GT='>' | GE='>=' | LT='<' | LE='<=' | CONTAINS='contains';
	public ComparisonOperatorElements getComparisonOperatorAccess() {
		return eComparisonOperator;
	}
	
	public EnumRule getComparisonOperatorRule() {
		return getComparisonOperatorAccess().getRule();
	}
	
	//Value returns adaptation::Value: StringValue | DecimalValue | IntegerValue | BooleanValue;
	public ValueElements getValueAccess() {
		return pValue;
	}
	
	public ParserRule getValueRule() {
		return getValueAccess().getRule();
	}
	
	//StringValue returns adaptation::StringValue: value=STRING;
	public StringValueElements getStringValueAccess() {
		return pStringValue;
	}
	
	public ParserRule getStringValueRule() {
		return getStringValueAccess().getRule();
	}
	
	//DecimalValue returns adaptation::DecimalValue: value=Decimal;
	public DecimalValueElements getDecimalValueAccess() {
		return pDecimalValue;
	}
	
	public ParserRule getDecimalValueRule() {
		return getDecimalValueAccess().getRule();
	}
	
	//IntegerValue returns adaptation::IntegerValue: value=Long;
	public IntegerValueElements getIntegerValueAccess() {
		return pIntegerValue;
	}
	
	public ParserRule getIntegerValueRule() {
		return getIntegerValueAccess().getRule();
	}
	
	//BooleanValue returns adaptation::BooleanValue: value=Boolean;
	public BooleanValueElements getBooleanValueAccess() {
		return pBooleanValue;
	}
	
	public ParserRule getBooleanValueRule() {
		return getBooleanValueAccess().getRule();
	}
	
	//SignedInt returns ecore::EInt: '-'? INT;
	public SignedIntElements getSignedIntAccess() {
		return pSignedInt;
	}
	
	public ParserRule getSignedIntRule() {
		return getSignedIntAccess().getRule();
	}
	
	//Long returns ecore::ELong: '-'? INT;
	public LongElements getLongAccess() {
		return pLong;
	}
	
	public ParserRule getLongRule() {
		return getLongAccess().getRule();
	}
	
	//Decimal returns ecore::EBigDecimal: '-'? INT '.' INT;
	public DecimalElements getDecimalAccess() {
		return pDecimal;
	}
	
	public ParserRule getDecimalRule() {
		return getDecimalAccess().getRule();
	}
	
	//Boolean returns ecore::EBoolean: 'true' | 'false';
	public BooleanElements getBooleanAccess() {
		return pBoolean;
	}
	
	public ParserRule getBooleanRule() {
		return getBooleanAccess().getRule();
	}
	
	//Action returns adaptation::Action: 'action' type=ActionType parameters=AdaptationParameters?;
	public ActionElements getActionAccess() {
		return pAction;
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}
	
	//AdaptationParameters returns adaptation::AdaptationParameters:
	// 'level' hintLevel=HintLevel ('style' feedbackStyle=FeedbackStyle)? |
	// 'style' feedbackStyle=FeedbackStyle ('level' hintLevel=HintLevel)?;
	public AdaptationParametersElements getAdaptationParametersAccess() {
		return pAdaptationParameters;
	}
	
	public ParserRule getAdaptationParametersRule() {
		return getAdaptationParametersAccess().getRule();
	}
	
	//enum ActionType returns adaptation::ActionType:
	// SHOW_HINT | CHANGE_HINT_LEVEL | REPEAT_ACTIVITY | SELECT_REINFORCEMENT_ACTIVITY |
	// ADVANCE_TO_NEXT_CONCEPT | INCREASE_DIFFICULTY | DECREASE_DIFFICULTY |
	// SHOW_CODE_VIEW | HIDE_CODE_VIEW | CHANGE_FEEDBACK_STYLE;
	public ActionTypeElements getActionTypeAccess() {
		return eActionType;
	}
	
	public EnumRule getActionTypeRule() {
		return getActionTypeAccess().getRule();
	}
	
	//enum HintLevel returns adaptation::HintLevel: CONCEPTUAL | GUIDED | DIRECT;
	public HintLevelElements getHintLevelAccess() {
		return eHintLevel;
	}
	
	public EnumRule getHintLevelRule() {
		return getHintLevelAccess().getRule();
	}
	
	//enum FeedbackStyle returns adaptation::FeedbackStyle: CONCISE | EXPLANATORY;
	public FeedbackStyleElements getFeedbackStyleAccess() {
		return eFeedbackStyle;
	}
	
	public EnumRule getFeedbackStyleRule() {
		return getFeedbackStyleAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
