/*
 * generated by Xtext
 */
package com.project.mde.adaptation.dsl.parser.antlr;

import com.google.inject.Inject;
import com.project.mde.adaptation.dsl.parser.antlr.internal.InternalAdaptationRulesParser;
import com.project.mde.adaptation.dsl.services.AdaptationRulesGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class AdaptationRulesParser extends AbstractAntlrParser {

	@Inject
	private AdaptationRulesGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAdaptationRulesParser createParser(XtextTokenStream stream) {
		return new InternalAdaptationRulesParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "AdaptationRuleSet";
	}

	public AdaptationRulesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AdaptationRulesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
