/*
 * generated by Xtext
 */
package com.project.mde.adaptation.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AdaptationRulesAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/project/mde/adaptation/dsl/parser/antlr/internal/InternalAdaptationRules.tokens");
	}
}
